### ISSUE TITLE
Best way to resolve Warning: use of proxy(new_value) to set connection proxy have been DEPRECATED and will be removed in Faraday 1.0

### ISSUE THREAD

**Issue by damienh** [lostisland/faraday#1008]
Hey,

I am currently using version `0.15.4` and I am seeing this deprecation notice 

```
Warning: use of proxy(new_value) to set connection proxy have been DEPRECATED and will be removed in Faraday 1.0
```

This is because I am using `.proxy` when calling `Faraday.new`. 

I have had a look through the repo, but I cannot work out an alternative way to implement the use of a proxy. What way would you recommend for version 1.0+.

**Comment by iMacTia** [comment]
Hi @damienh, that is because before before v1.0 you could use the `proxy` method to both GET and SET the proxy.

```
conn.proxy
#=> Returns the current proxy

conn.proxy(proxy_options)
#=> Sets the proxy using proxy_options
```

However, that's not allowed anymore and in v1.0 you should now use `proxy=` when you set the proxy. You can see the implementation here: https://github.com/lostisland/faraday/blob/master/lib/faraday/connection.rb#L397

If you're calling `proxy` with no parameters, you should not see this warning though

**Comment by damienh** [comment]
Great that worked. Thank you @iMacTia
