### ISSUE TITLE
How to send Cookie along with Faraday.get/post

### ISSUE THREAD

**Issue by jdescelliers** [lostisland/faraday#1011]
## Basic Info

* Faraday Version: 0.13.1
* Ruby Version: 2.4.2

## Issue description
Is this possible to clearly document how to send cookies along with an HTTP request?

The documentation is quite unclar about that.

**Comment by iMacTia** [comment]
Hi @jdescelliers, that's because Cookies are just headers so there's nothing special about Faraday that needs documenting 😄. If you want to see how to correctly set the Cookie header, then you can check the [Mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie).

If you're talking about automatically storing cookies from a response and use them into a subsequent request (similar to what browsers do), then there's a handy 3rd party gem for that: https://github.com/miyagawa/faraday-cookie_jar
