### ISSUE TITLE
Faraday w/ Net::HTTP adapter repeats request with body from first request response

### ISSUE THREAD

**Issue by anaulin** [lostisland/faraday#1016]
## Basic Info

* Faraday Version: 0.12.1
* Ruby Version: 2.3.4

## Issue description

I observe Faraday doing a second, unwanted, HTTP request, containing as body the contents of the response body of a first request. This behavior goes away if I create the Faraday connection providing a block (even if the block is empty).

Faraday connection creation with odd behavior:
```
client = Faraday.new(conn_options)

# Is seen to make two requests to same URL.
# Second request has body containing response from first request.
client.post(....)  
```

I can remove the odd behavior by instead doing:
```
client = Faraday.new(conn_options) do |faraday|
  # Block intentionally left blank.
end

# Now makes only one HTTP request.
client.post(....)  
```

I have traced this issue as far as this piece of code in the Net::HTTP adapter: https://github.com/lostisland/faraday/blob/master/lib/faraday/adapter/net_http.rb#L61-L70
The call to `@app.call env` on line 70 calls again the Net::HTTP adapter and ends up doing the second request with the wrong environment.

I also wonder if this behavior is related to this line in the Faraday constructor:
```
@builder = options.builder || begin
        # pass an empty block to Builder so it doesn't assume default middleware
        options.new_builder(block_given? ? proc { |b| } : nil)
      end
```
Source: https://github.com/lostisland/faraday/blob/master/lib/faraday/connection.rb#L77-L80

It is possible that I'm missing something in Faraday configuration or usage, and this is expected behavior. Any guidance you have is much appreciated.

## Steps to reproduce
See above, in the description.

**Comment by technoweenie** [comment]
Hi @anaulin :wave: I'm unable to reproduce this locally. This looks like you're hitting some kind of HTTP retry behavior. What HTTP response are you getting from the server? Is a timeout being raised?

@iMacTia let me know that the net/http library has built-in retry capabilities for timeouts. Faraday v0.15.4 already disables this behavior in favor of the optional Faraday Retry middleware:

https://github.com/lostisland/faraday/blob/f4ae96ea9b7850f0c2bf03a101b0d0beda8a1049/lib/faraday/adapter/net_http.rb#L179-L180

However, this won't help even if you upgrade from Faraday v0.12.1 since `max_retries` can only be changed in Ruby 2.5+. 

You can probably get around this by extending the timeout when setting up the faraday object.

```ruby
conn_options = {
  :request => {
    :timeout => 5, # in seconds
  },
}
client = Faraday.new(conn_options)
```

If your requests aren't timing out, then I'd have to see how your Faraday client is setup. What is `conn_options` in your case? Of course, please remove sensitive details, change urls, etc :) I'm mostly interested in how the adapter and any middleware are configured.

## Faraday v0.12.1 example

```
$ sudo gem install faraday -v 0.12.1
Fetching: faraday-0.12.1.gem (100%)
Successfully installed faraday-0.12.1
Parsing documentation for faraday-0.12.1
Installing ri documentation for faraday-0.12.1
Done installing documentation for faraday after 1 seconds
1 gem installed

$ irb
>> require 'rubygems'
=> false

>> gem 'faraday','0.12.1'
=> true
>> require 'faraday'
=> true
>> Faraday::VERSION
=> "0.12.1"

>> f=Faraday.new 'https://endefyg02xbqt.x.pipedream.net'
=> #<Faraday::Connection:0x00007fd6848852b8 ...>

>> f.post '/hewwo', Time.now.utc.to_s
=> #<Faraday::Response:0x00007fd68592a730 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:post @body="{\"success\":true}" @url=#<URI::HTTPS https://endefyg02xbqt.x.pipedream.net/hewwo> @request=#<Faraday::RequestOptions (empty)> @request_headers={"User-Agent"=>"Faraday v0.12.1", "Content-Type"=>"application/x-www-form-urlencoded"} @ssl=#<Faraday::SSLOptions verify=true> @response=#<Faraday::Response:0x00007fd68592a730 ...> @response_headers={"access-control-allow-origin"=>"*", "content-type"=>"application/json; charset=utf-8", "date"=>"Thu, 05 Sep 2019 19:18:52 GMT", "x-pd-status"=>"sent to primary", "x-powered-by"=>"Express", "content-length"=>"16", "connection"=>"Close"} @status=200 @reason_phrase="OK">>
```

([my requestbin](https://requestbin.com/r/endefyg02xbqt/1QQmKpLzCGpnKv9cvi0yv6bRKxa))

**Comment by anaulin** [comment]
Hi @technoweenie 👋. Thank you for the quick follow-up!

I don't think it is related to retries exactly, because the body of the request gets changed between requests.

Your example above doesn't reproduce for me either, but adding a setting related to the Net::HTTP adapter seems to make a difference. Here is an example that reproduces for me (and link to request bin):

```
$ irb
> gem 'faraday','0.12.1'
=> true

> require 'faraday'
=> true

> Faraday::VERSION
=> "0.12.1"

> conn = Faraday.new(url: "https://enerqpylt8gum.x.pipedream.net")
=> #<Faraday::Connection:0x007fa4c00d8a10 @parallel_manager=nil, @headers={"User-Agent"=>"Faraday v0.12.1"}, @params={}, @options=#<Faraday::RequestOptions (empty)>, @ssl=#<Faraday::SSLOptions (empty)>, @default_parallel_manager=nil, @builder=#<Faraday::RackBuilder:0x007fa4c10dfd78 @handlers=[Faraday::Request::UrlEncoded, Faraday::Adapter::NetHttp]>, @url_prefix=#<URI::HTTPS https://enerqpylt8gum.x.pipedream.net/>, @proxy=nil>

> conn.adapter :net_http do |http|
*   http.open_timeout = 30
> end
=> [Faraday::Request::UrlEncoded, Faraday::Adapter::NetHttp, Faraday::Adapter::NetHttp]

> conn.post '/willitblend', Time.now.utc.to_s
=> #<Faraday::Response:0x007fa4c11d68a8 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:post @body="{\"success\":true}" @url=#<URI::HTTPS https://enerqpylt8gum.x.pipedream.net/willitblend> @request=#<Faraday::RequestOptions (empty)> @request_headers={"User-Agent"=>"Faraday v0.12.1", "Content-Type"=>"application/x-www-form-urlencoded"} @ssl=#<Faraday::SSLOptions verify=true> @response=#<Faraday::Response:0x007fa4c11d68a8 ...> @response_headers={"access-control-allow-origin"=>"*", "content-type"=>"application/json; charset=utf-8", "date"=>"Thu, 05 Sep 2019 21:14:38 GMT", "x-pd-status"=>"sent to primary", "x-powered-by"=>"Express", "content-length"=>"16", "connection"=>"Close"} @status=200 @reason_phrase="OK">>
```

You can see the two requests that got sent in the requestbin, one with the body you'd expect, and one with body `"success": true`: https://requestbin.com/r/enerqpylt8gum/1QR0PWrdDdP6NTXTTJZKF1maDBu

**Comment by technoweenie** [comment]
Oh, thanks for providing a failing example. I found a hint in the code output:

```
> conn.adapter :net_http do |http|
*   http.open_timeout = 30
> end

# Two NetHttp adapters???
=> [Faraday::Request::UrlEncoded, Faraday::Adapter::NetHttp, Faraday::Adapter::NetHttp]
```

The `#adapter` method adds an adapter middleware to the stack. Since the original `Faraday.new` didn't set one, Faraday sets it to the configured default adapter. The extra `conn.adapter` call in the example then adds a second one.

The `adapter` method is intended to be called inside the `Faraday.new` block:

```ruby
conn = Faraday.new(url: "url") do |builder|
  builder.adapter :net_http do |http|
    http.open_timeout = 30
  end
end

# you can double check the configured handlers
conn.builder.handlers
# => [Faraday::Adapter::NetHttp]
```

I hope this helps! As far as Faraday going forward, I'll discuss with the team about what we can do about this for Faraday v1.0. There are a number of options, but we are being careful about unintended breakage too. Any discussion of it will reference this issue, in case you're interested in following along.

**Comment by anaulin** [comment]
Yes, this was the issue. Changing the code to initialize the adapter in the `Faraday.new` call does solve the problem.

Thanks again for your help, @technoweenie ! 🌟
