### ISSUE TITLE
Getting Faraday response of invalid user but when making same call from CURL, its getting updated. 

### ISSUE THREAD

**Issue by Ronak5** [lostisland/faraday#1019]
Getting Faraday response of invalid user but when making same call from CURL, its getting updated. 

* Faraday Version: 0.9.1
* Ruby Version: 2.4.4

## Issue description

Faraday call 

```ruby
@conn = Faraday.new(:url => Settings.cleartrip_extranet_endpoint) do |faraday|
  faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
  faraday.headers['Content-Type'] = 'application/xml'
  faraday.headers['X-CT-API-KEY'] = Settings.cleartrip_extranet_key
  faraday.headers['X-CT-SOURCETYPE'] = 'API'
end
```

Request
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<hotel-room-types xmlns="http://www.cleartrip.com/extranet/hotel-room-types" type="get">
  <hotel-id><hotel_id></hotel-id>
Response
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<hotel-room-type-response xmlns="http://www.cleartrip.com/extranet/hotel-room-types-response">
    <hotel-id><hotel_id></hotel-id>
    <status>
        <code>E002</code>
        <description>Invalid User</description>
    </status>
</hotel-room-type-response>
```

```shell
curl -X POST \
  https://api.cleartrip.com/chmm/service/get-room-types \
  -H 'content-type: application/xml' \
  -H 'x-ct-api-key: <key> \
  -H 'x-ct-sourcetype: API' \
  -d '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<hotel-room-types xmlns="http://www.cleartrip.com/extranet/hotel-room-types" type="get">
  <hotel-id><hotel id ></hotel-id>
</hotel-room-types>'
```

In this we are getting correct response

**Comment by iMacTia** [comment]
Hi @Ronak5, wow that's quite an old version of Faraday, but let me see if I can help.
The first thing I'd suggest to do is to add some logging so we can see if there's anything missing in the request.
You can add the logger middleware to your request while building your stack:

```ruby
@conn = Faraday.new(:url => Settings.cleartrip_extranet_endpoint) do |faraday|
  faraday.headers['Content-Type'] = 'application/xml'
  faraday.headers['X-CT-API-KEY'] = Settings.cleartrip_extranet_key
  faraday.headers['X-CT-SOURCETYPE'] = 'API'
  faraday.response :logger
  faraday.adapter  Faraday.default_adapter
end
```

Please try adding it and check the logs to see the request URL and headers.
There are different things that might go wrong here:

1. The `Settings.cleartrip_extranet_key` might not be set (least likely as I assume you checked that)
2. The server you're calling is case-sensitive on headers: that shouldn't be the case, but some servers are. I noticed that you used lower-cased headers name in cURL, so that might also be an issue
3. Faraday is not setting the headers for some reason

**Comment by Ronak5** [comment]
hi @iMacTia  we added logs and verified body & headers at our server. 

We talked to cleartrip team, they are saying might be faraday is adding some other fields in the header so might give an invalid user. 

For above-mentioned possibilities:- 
1. Settings.cleartrip_extranet_key is checked. 
2. We tried making the call in both caps & in small letters, the response is the same
3. Faraday header are set as we are making calls to other OTAs in the same manner.

**Comment by iMacTia** [comment]
@Ronak5 given the `logger` middleware is placed just before the adapter in the stack, Faraday should be making any change to headers or body before passing them over to the `Net::HTTP` adapter. If looking at the headers in the logs you still don't see any issue, it may be that `Net::HTTP` is doing something wrong.
So I'd suggest the following steps:

1. Share the (sanitised) headers that you see in the logs here so we can have a look and hopefully spot something
2. Try making a successful request using `Net::HTTP` only

**Comment by webkreators** [comment]
Hi @iMacTia,

Thank You!

Below are the headers we are sending:

faraday.adapter  Faraday.default_adapter
faraday.headers['Content-Type'] = 'application/xml'
faraday.headers['X-CT-API-KEY'] = Settings.cleartrip_extranet_key
faraday.headers['X-CT-SOURCETYPE'] = 'API'

When we have accessed the headers we found the keys are changed 

CONTENT_TYPE => application/xml
HTTP_X_CT_API_KEY => xxxxxxxxxxxxxxxxxxx1233456789
HTTP_X_CT_SOURCETYPE => API

Can you please guide us how to send the exact headers or some flags so that the headers remain the same.

Regards,
Ravindra

**Comment by Ronak5** [comment]
so when passing faraday.headers['X-CT-API-KEY'] 
header is updating it to  HTTP_X_CT_API_KEY => xxxxxxxxxxxxxxxxxxx1233456789 

This can create an issue.

**Comment by webkreators** [comment]
Hello @iMacTia,

We are very close to the solution. We need to pass **x-ct-sourcetype** as key in the header but while retrieving it converts to **X-Ct-Api-Key**. Can you please guide us if we can update any settings so that the header key doesn't get capitalized automatically?

Regards,

**Comment by technoweenie** [comment]
That sounds like your web server is enforcing consistent casing in the header values. It makes sense that you'd access ` HTTP_X_CT_API_KEY` on the server, when api clients can send the key as `X-CT-API-KEY` or just `x-ct-api-key` (such as in the ruby and curl examples above). How is the key accessed from the `curl` example, when it's sent all lower case?

**Comment by webkreators** [comment]
It is being accessed as **x-ct-api-key** at the API end.

**Comment by iMacTia** [comment]
OK so in the end it was a capital cases issue 😄! Which is one of the possible issues I listed above

> The server you're calling is case-sensitive on headers: that shouldn't be the case, but some servers are. I noticed that you used lower-cased headers name in cURL, so that might also be an issue

Good news is that that has already been asked, bad news is that it's not Faraday's fault:
https://github.com/lostisland/faraday/issues/747#issuecomment-439864181

If you read my comment above, you'll see that it's actually `Net::HTTP` (the default adapter) the one enforcing the standard by changing the headers.

I can only think about 3 possible solutions:
1. Fix the server so that it complies with the standard and manages headers in a case-insensitive way
2. Use a different adapter (apparently Typhoeus doesn't have this issue, but I'd try Patron as well as it should be cURL-based)
3. Raise this issue with the Ruby team to fix or provide an option to avoid this in Net::HTTP

I'll close this issue assuming we identified the issue and 3 possible solutions, however feel free to follow up if you need any more help

**Comment by Ronak5** [comment]
Thank you
