### ISSUE TITLE
Breaking change for octokit in 0.16.1

### ISSUE THREAD

**Issue by Vedrillan** [lostisland/faraday#1033]
## Basic Info

* Faraday Version: 0.16.1
* Ruby Version: 2.6.4

## Issue description
Been having issues related to faraday with a new project using octokit.
```
~/.rvm/gems/ruby-2.6.4/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14:in `<module:Middleware>': superclass must be a Class (Faraday::DeprecatedConstant given) (TypeError)
```
Tested with 0.15.4 and there is no issue there.
If it is a desired breaking change then let me know, I will gladly report this to the octokit repository, maybe they will freeze faraday usage to a compatible version.

## Steps to reproduce
Create a new ruby file, install octokit, which will depends at some point on faraday latest, then at line `require octokit` this error will happen.

**Comment by marklchaves** [comment]
I ran into this issue yesterday. It broke my dev site. Just updated to 0.16.2. My dev site is back up. I.e., no more `superclass must be a Class (Faraday::DeprecatedConstant given)` error.

**Comment by iMacTia** [comment]
Hello everyone, we are really sorry for all the disruptions caused by the v0.16.x releases.
We've just performed a ROLLBACK RELEASE v0.17.0 which follows directly the latest working release v0.15.4.
Please update to that version to solve the backwards-compatibility issues.
More info here: https://github.com/lostisland/faraday/releases/tag/v0.17.0
