### ISSUE TITLE
Get http request for permanent spring page

### ISSUE THREAD

**Issue by sydneyfunnelAIO** [lostisland/faraday#1070]
## Basic Info

* Faraday Version:0.17.0
* Ruby Version:2.5.6

## Issue description
hey. i need request from http. but this page permanent refresh . how can i get it.
i have a video : https://youtu.be/xHBb2Tl-q_M
i can reach all features when its not respring. is it a javascript or anything how can i get it ? thx

## Steps to reproduce
my code:
![image](https://user-images.githubusercontent.com/51324523/68069615-8838c900-fd73-11e9-81c7-3adfc0bb76ee.png)

Sorry i m new on this side....

**Comment by iMacTia** [comment]
Hi @sydneyfunnelAIO, those are called streaming responses.
We have only just recently added their support to Faraday, so it's only available in Faraday v1.0.
Version 1.0 is not officially released yet, although we hope that will happen before the end of the year. You can start using the [Release Candidate](https://github.com/lostisland/faraday/releases/tag/v1.0-rc1) though, so that when v1.0 will be release you'll be ready to use it.

You can find details on how to use them [here](https://lostisland.github.io/faraday/usage/streaming).
Please note only the `Net::HTTP` supports this now, but it seems like you're using it anyway so that should be fine.
