### ISSUE TITLE
Documentation should provide a clearer list of pages

### ISSUE THREAD

**Issue by vvo** [lostisland/faraday#1110]
## Basic Info

Even if I went multiple times to the website, I first completely missed the fact that there are actually more pages than the ones here:
![image](https://user-images.githubusercontent.com/123822/72051089-d661cf80-32c2-11ea-95be-3509c96c7fd7.png)

For example I was looking for the retry documentation and could not find it but in GitHub, because to access it you need to do this:
1. Click on middleware
2. Click at the bottom for "Available middleware"
3. Click on the retry middleware

Step 2. is the easy one to miss because the link is not obvious.

I would propose to have something like this instead:

![image](https://user-images.githubusercontent.com/123822/72051555-d0b8b980-32c3-11ea-92f0-9b9c217076f0.png)

Or in general, a way to visualize easily all the documentation links without having to scroll down etc..

PS: I worked previously at Algolia, they provide this service for documentation websites: https://community.algolia.com/docsearch/. Would you like it implemented on the faraday website? I can help with that!

**Comment by iMacTia** [comment]
That looks interesting!

We picked GitHub-pages because it was a quick and free hosting for our pages, plus we could build/style the docs with Jekyll and keep them under version control.
However this was the first time for us using it, and we quickly hit some limitations (possibly due to our inexperience with it).

If Algolia is compatible with Jekyll and GitHub-pages, then it would be a great addition to the website, so I'd happily take your kind offer and see how we can add it in 😃
