### ISSUE TITLE
Viewing the TLS cert from the response 

### ISSUE THREAD

**Issue by BobbyMcWho** [lostisland/faraday#1128]
I know faraday does some cert validity verification under the hood when receiving responses, but is there any way to access the raw cert information from the response if I wanted to parse information about it manually as part of say a response middleware?

**Comment by iMacTia** [comment]
Not that I know of!

It's worth noting that Faraday does not actually implement any validation per se, it simply allows you to configure the adapter so that you can run the validation you need (for example for `Net::HTTP` you can set `verify_mode` to what you want).

However Faraday does not provide you direct access to the underlying response object, and there's no standardised way to accessing that information since each adapter has a different underlying implementation.

This sounds to me like a very specific case, as you should be able to rely on the adapter's capabilities to verify the certificate.
I'd like to hear more about the exact use-case before deciding if it's worth exploring this more

**Comment by BobbyMcWho** [comment]
Ah, I see. Probably not something that would work as a faraday middleware then. 

I had a middleware gem idea I was gonna hack on, to check cert expiration date when we receive a response, and provide a middleware block so the user could print to STDOUT, log to sentry, _whatever_ if the cert was expiring within, 1, 7, _whatever_ days threshold. Sort of a way to responsibly keep tabs on your external dependencies and alert you so you can contact them or whatever to make sure your service isn't ultimately affected.

**Comment by iMacTia** [comment]
Oh I see, it doesn't sound like a bad idea at all actually 😄.

However as I mentioned above the issue is that in order to do so you'll most probably need to access the adapter "raw" response (rather than the faraday response currently returned) and have a custom implementation for each of them. So your middleware will most probably not be compatible with all adapters as there are custom-made ones as well outside the core team control.

A first step towards making this possible would be to create a new adapter API to fetch the response certificate as well, and store it in the `env` variable (see `save_response` for what we save at the moment), but would still rely on all adapters (including custom-made ones) to implement such a change.

Although it sounds a good idea and possible on paper, I'd say it would take a good amount of time to get such a change embraced by all adapters
