### ISSUE TITLE
Ruby 1.9 support for the Net::HTTP::Persistent adapter

### ISSUE THREAD

**Issue by horgh** [lostisland/faraday#1165]
## Basic Info

* Faraday Version: 0.17.3
* Ruby Version: ruby-1.9.3-p551

## Issue description

I have a gem that supports back to Ruby 1.9. I've recently switched it to use the Net::HTTP::Persistent adapter, but I found that with Faraday 0.17.3, there is a syntax error:

```
      builder.adapter :net_http_persistent, pool_size: 5 do |http|
         http.idle_timeout = 30
       end
     
     SyntaxError:
       /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.17.3/lib/faraday/adapter/net_http_persistent.rb:13: syntax error, unexpected tPOW, expecting ')'
                   Net::HTTP::Persistent.new(**options)
```

I have a Travis build showing this here: https://travis-ci.com/github/maxmind/minfraud-api-ruby/jobs/361407866

I am aware Ruby 1.9 is old and end of life'd, and this is for an old Faraday version, so perhaps there's little interest in fixing it, but I thought I'd let you know. I'm likely going to drop Ruby 1.9 support from my gem to work around this, so I'm ok with closing this issue!

## Steps to reproduce

Use Faraday 0.17.3 with the Net::HTTP::Persistent adapter on Ruby 1.9.

Thank you!

**Comment by iMacTia** [comment]
Hi @horgh, I'm really sorry about this and trust me, I know the pain you're going through.
With Faraday 1.0 we took the opportunity to drop the EOL Ruby versions, while on 0.17 we did our best to keep as much of them as possible. My last attempt with 1.9 was back from last December: https://github.com/lostisland/faraday/pull/1087#issuecomment-569292234

I tried and tried, but I was only able to make it work with 2.0+.
If I remember correctly, the biggest issues were not even related to the syntax, but rather on the dependencies that had abandoned Ruby 1.9 many years back. We decided to drop Ruby 1.9 at that point because it was becoming too expensive to maintain.

I'd still like to help if possible, so here are 3 alternatives I can suggest:

1. Update your gem and drop Ruby 1.9 as well. If that's not a big issue, this would be the easiest by far. Your users can always lock their gem version to the last one supporting Ruby 1.9, if really necessary. We were scared about doing this as well but actually almost no one complained when we dropped it from Faraday.
2. If we want to fix this in Faraday, we should do it properly: create a PR from the 0.1x branch and add Ruby 1.9 back into the CI, then update the code until all tests are green. This is probably be the hardest. I tried and failed miserably.
3. Fork Faraday 0.17 and make just the changes you need to make it work on your gem, then use your fork. No need to open PRs, request approval or fix CI issues! I'd usually never suggest this route, but reality is that branch 0.1x's last commit is from February and it will hardly be updated in future, so it actually makes sense in this case!

If you decide to go with solution 2, feel free to request my review on the PR

**Comment by horgh** [comment]
Hi @iMacTia! Thank you so much for taking the time to help! It sounds like it you've put a lot of effort into this area already 😄.

I think I will go with your option 1. As you say, people can still opt to use older versions of my gem until they're able to update. Trying to get everything working to support 1.9 sounds like it'd be quite hard!

I'll go ahead and close this then. Thanks again for your assistance, I really appreciate it!
