### ISSUE TITLE
Faraday returning results of other request?

### ISSUE THREAD

**Issue by mcjansen** [lostisland/faraday#1216]
## Basic Info

* Faraday Version: 1.0.1
* Ruby Version: 2.6.6

## Issue description
I have noticed some bizarre behavior in our Rails 6 / Elastic-search-ruby/ Elastic Cloud on Kubernetes setup, that is using Faraday under the hood.

Once or twice per hour, a user receives the results of a query that was executed by another user. I haven't found a way to reproduce it. At this moment, I can only detect it after the event.

Has anybody experienced this before when using Faraday? It feels a bit like a threading issue.

I am using the standard setup and haven't started using Patron or Typhoeus. Could it be related to that?

I also posted this issue a couple of days ago in the elastic-search-ruby project, but didn't got an answer yet.
https://github.com/elastic/elasticsearch-ruby/issues/1131

Any help would be appreciated.

**Comment by iMacTia** [comment]
Hi @mcjansen, I'm not sure I can help but I can tell you that the default adapter `:net_http` doesn't use any parallelisation or reuse any connection. Every request is individually executed through the use of a new connection.
For that reason, I highly doubt there's any sort of concurrent access to a memory object or socket connection.

This could either be a logical issue or something due to the setup of the connection in elastic-search-ruby.
But without further information it's quite  hard to help.

**Comment by mcjansen** [comment]
Thanks!

I finally found an issue in my own Ruby code that caused this to happen.
