### ISSUE TITLE
How to specify a keepalive time interval?

### ISSUE THREAD

**Issue by rgaufman** [lostisland/faraday#1217]
We are using this code:

```
Faraday.new(uri) do |f|
  f.adapter :net_http_persistent
end
```

The manufacturer of this device is saying the keep-alive interval needs to be 5 seconds, otherwise the connection times out.

This is working correctly with curl with this parameter:

```
Romans-MacBook-Air.local ➜  curl --help | grep -i alive
     --keepalive-time <seconds> Interval time for keepalive probes
```

For example:

```
curl -vvv --digest -u admin:admin123 --keepalive-time 4 -XGET 'http://admin:admin123@192.168.88.15/cgi-bin/snapManager.cgi?action=attachFileProc&Flags%5B0%5D=Event&Events=%5BAll%5D'
```

But with Faraday, the connection times out because a keepalive is not sent within 5 seconds.

I'm not able to find documentation how to specify the keepalive interval?

**Comment by iMacTia** [comment]
Hi @rgaufman, unfortunately Faraday doesn't support that configuration natively due to the inconsistency on the underlying adapters.

HOWEVER, if you know how to configure your adapter (`net_http_persistent`) to do it, you can access the connection instance directly following this documentation page: https://lostisland.github.io/faraday/adapters/net-http-persistent
In the example above the `idle_timeout` setting is configured, but you can access all the other `Net::HTTP::Persistent` properties as well from there.

Alternatively, you might want to switch to Typhoeus, which is a cURL based adapter. It seems you can definitely do what you want with that one: https://stackoverflow.com/q/43852419/4194669
> Edit: I was able to work around this by switching to Typhoeus (which wraps cURL) and passing the option tcp_keepalive: true to my requests, which is the flag that tells cURL to send keepalive probes.


Please let me know if this helps!

**Comment by rgaufman** [comment]
This helped, thank you!
