### ISSUE TITLE
Missing from RubyDoc.info

### ISSUE THREAD

**Issue by nickcampbell18** [lostisland/faraday#1235]
## Basic Info

* Faraday Version: master
* Ruby Version: 2.7

## Issue description

This gem doesn't appear to be building on RubyDoc.info anymore: https://www.rubydoc.info/gems/faraday

## Steps to reproduce

1. Visit https://www.rubydoc.info/gems/faraday, gem is absent

**Comment by iMacTia** [comment]
Hey @nickcampbell18 thanks for reporting this!
I managed to find it here: https://www.rubydoc.info/github/lostisland/faraday

To be honest I have no idea how Rubydoc.info is supposed to work, what is the expected URL, and what we need to do in order to feature there or debug this issue.
Any info you might provide to help us out?

**Comment by nickcampbell18** [comment]
😆 to be honest, I'm not 100% sure either - maybe we should just repoint the link in the README? Would you like me to open a PR?

**Comment by olleolleolle** [comment]
@nickcampbell18 It would be awesome if you opened a PR to update that!
