### ISSUE TITLE
How to disable host name verification while keeping peer verification using certificates

### ISSUE THREAD

**Issue by donv** [lostisland/faraday#1408]
Hi all!

We are using Faraday in an IoT system, and it is really great!  Thank you for an excellent library!

We need to connect to devices with unpredictable IP-addresses, but we still need to authenticate them using certificates.  The device's server certificate subject name will naturally not match the request host name, and currently the peer certificate verification fails on host name mismatch.

Is there a way to disable the host name verification while still keeping the peer certificate verification?

Please feel free to direct me to relevant documentation.  I realize this is a general http/ruby/openssl problem, but I have been unable to find any documentation allowing this use case.

**Comment by donv** [comment]
Hi all!

I have found one workaround and one proposed solution.

The workaround is to redefine the Ruby SSL connection defaults to disable host name verification:

```ruby
OpenSSL::SSL::SSLContext::DEFAULT_PARAMS[:verify_hostname] = false
```

This works, but changes the default for all Ruby SSL connections, which is undesirable.

My proposed solution is to add the `verify_hostname` ssl option to Faraday and propagate it to Ruby SSL.  Does this sound like a good solution?  I can submit a pull request if you think this is the way forward.

**Comment by iMacTia** [comment]
Hi @donv and thanks for opening this, glad to hear you're finding Faraday useful 🙏!

Good news: [A PR was already opened](https://github.com/lostisland/faraday/pull/1172) to tackle this exact issue 🎉 !

Bad news: The PR got stalled because at the time Faraday was shipping with a bunch of adapters, and any change to the API would require updating all adapters accordingly. Sadly, some HTTP libraries didn't have support for this feature.

Good news: But Faraday 2.0 has pushed adapters into standalone libraries and created the chance to introduce new features without having to address all adapters at the same time 👏!

The quickest path for that PR to be merged would be to rebase it against the `main` branch and only keep the change for the Faraday API (i.e. the new SSL option).
We could then open another PR against https://github.com/lostisland/faraday-net_http that handles this new option.
Once both PRs are merged and released, you'll be able to use the new option.

This is obviously assuming you're using the default `net_http` adapter and you're able to upgrade your project to Faraday 2.0+.

I'm a bit swamped at the moment so I won't have the chance to work on this immediately, but the work is already there in the PR so anyone could pick this up for a split and rebase 🙌

**Comment by hyuraku** [comment]
@iMacTia 
It seems to me that this PR has been solved by https://github.com/lostisland/faraday/pull/1428, would you like to close this?

**Comment by UweKubosch** [comment]
Yes, please go ahead and close.

**Comment by olleolleolle** [comment]
Thanks, @hyuraku, good eye!
