### ISSUE TITLE
Faraday 2.7.1 causes following warning: "warning: method redefined; discarding old error"

### ISSUE THREAD

**Issue by wuarmin** [lostisland/faraday#1467]
Hey!
## Basic Info

* Faraday Version: 2.7.1
* Ruby Version: 3.1.0

## Issue description
I get following warning
```txt
/usr/local/bundle/gems/faraday-2.7.1/lib/faraday/logging/formatter.rb:40: warning: method redefined; discarding old error
/usr/local/lib/ruby/3.1.0/forwardable.rb:229: warning: previous definition of error was here
```

## Steps to reproduce
If I execute following code, the warning appears.
```ruby
Faraday.new(url: Test::Slice[:settings].endpoint, headers: { "Content-Type" => "application/xml" }) do |conn|
  conn.use XMLMiddleware
end
```

Thanks and best regards

**Comment by iMacTia** [comment]
Hi @wuarmin, the error is a bit strange because `logging/formatter.rb` should only be used if you also add the `:logger` middleware to your connection.

1. Is that the whole connection initialisation block or are you leaving out something else?
2. Can you share the code for the `XMLMiddleware`? Is that a custom middleware?
