### ISSUE TITLE
ArgumentError due to missing ruby2_keywords on Ruby 3.2.0

### ISSUE THREAD

**Issue by anero** [lostisland/faraday#1479]
## Basic Info

* Faraday Version: 1.10.2
* Ruby Version: 3.2.0

## Issue description
When adding a middleware that receives keyword arguments in the constructor, the call from [`DependencyLoader#new`](https://github.com/lostisland/faraday/blob/1.x/lib/faraday/dependency_loader.rb#L21) fails because the method is not defined using `ruby2_keywords`. I noticed that this was first added in https://github.com/lostisland/faraday/pull/1153 but then got removed in https://github.com/lostisland/faraday/pull/1211, mentioning that ruby 2.7 did't display any warnings when removing `ruby2_keywords`.
I think that with the change on Ruby 3.2.0 (related to bugs https://bugs.ruby-lang.org/issues/18625 and https://bugs.ruby-lang.org/issues/16466) this no longer works. This is also demonstrated by running the `spec/faraday/rack_builder_spec.rb` specs when targeting Ruby 3.2.0.

I can submit a small PR with this change targeting the `1.x` branch if that works for you.

## Steps to reproduce
Run `spec/faraday/rack_builder_spec.rb` specs on Ruby 3.2.0.

**Comment by serggl** [comment]
facing the same issue

**Comment by iMacTia** [comment]
Thank you @anero, I was reading through Ruby 3.2 release notes and figured this change might cause some issues.
At the time we decided to remove it because it wasn't causing any issues, but I agree we should now follow Ruby 3.2 requirements.

Please feel free to open a PR and address this. Ideally I'd like to fix the `main` branch first, and we can then backport the fix over to `1.x` as I assume the same issue would affect `main` as well?

It goes without saying we would need a test to demonstrate this as well. I'm surprised none of our tests failed but I guess that's because we never test adding a middleware with keyword arguments

**Comment by timrogers** [comment]
Fixed in #1483.

**Comment by olleolleolle** [comment]
And released! Closing this issue.
