### ISSUE TITLE
Incompatible with Firebase-admin-sdk

### ISSUE THREAD

**Issue by sirjackson** [lostisland/faraday#1499]
## Basic Info
Faraday  incompatible with firebase-admin-sdk
* Faraday Version:
* Ruby Version:
Bundler could not find compatible versions for gem "faraday":
  In snapshot (Gemfile.lock):
    faraday (= 2.7.1)

  In Gemfile:
    fcm was resolved to 1.0.8, which depends on
      faraday (>= 1.0.0, < 3.0)

    firebase-admin-sdk (~> 0.1.2) was resolved to 0.1.3, which depends on
      faraday (< 2)

    fcm was resolved to 1.0.8, which depends on
      googleauth (~> 1) was resolved to 1.3.0, which depends on
        faraday (>= 0.17.3, < 3.a)

    fcm was resolved to 1.0.8, which depends on
      googleauth (~> 1) was resolved to 1.3.0, which depends on
        signet (>= 0.16, < 2.a) was resolved to 0.17.0, which depends on
          faraday (>= 0.17.5, < 3.a)

**Comment by iMacTia** [comment]
Hi @sirjackson this looks like a dependency issue. If you check the versions listed, any version of Faraday 1.x would satisfy the constraint, but for some reason you have Faraday 2.7.1 in your Gemfile.lock. This can normally happen when a gem is added that restricts another gem's constraints.

The easiest solution is to just delete the Gemfile.lock and re-generate it. Otherwise you could try "bundle update faraday --conservative"

Please let me know if this helps 🙂
