### ISSUE TITLE
Any solution for Digest Auth in Faraday 2?

### ISSUE THREAD

**Issue by rgaufman** [lostisland/faraday#1555]
We are still using Faraday 1 because we cannot find a solution for Digest Auth. There is an old gem for faraday-digestauth but it only works with Faraday 1 and the maintainer has abandoned the project. Is there any solution please?

We are after something like this:

```
      @connection = Faraday::Connection.new do |conn|
        conn.adapter Faraday.default_adapter
        conn.request :digest, username, password
      end
```

**Comment by iMacTia** [comment]
@rgaufman I've always directed people to that gem because Faraday has never supported digest auth "out-of-the-box", but I didn't realise that was incompatible with Faraday 2.

I've left [a comment](https://github.com/bhaberer/faraday-digestauth/issues/17#issuecomment-2003876817) under your issue to ask the main maintainer of the gem if he's happy to get some help, and if he can add me as an owner to the rubygems gem for new releases.

Let's see what they reply and proceed from there. It shouldn't be hard to adapt the gem to work with Faraday 2.0.

**Comment by iMacTia** [comment]
It turns out [`faraday-digestauth`](https://github.com/bhaberer/faraday-digestauth) works just fine with Faraday 1.x and 2.x 🙌
