### ISSUE TITLE
Faraday.get can fail with certain URLs

### ISSUE THREAD

**Issue by myronmarston** [lostisland/faraday#258]
Here are a couple examples of URLs that fail for me:

```
1.9.3p327 :002 > Faraday.get("http://www.associatedasset.com/homeowner-resources/?Agritopia%A0Residential%A0Neighborhood%A0Owners%A0Association%2C%A0Inc.&ID=8")
ArgumentError: invalid byte sequence in UTF-8
    from /Users/myron/code/vanguard/bundle/ruby/1.9.1/gems/faraday-0.8.7/lib/faraday/utils.rb:215:in `normalize_params'
    from /Users/myron/code/vanguard/bundle/ruby/1.9.1/gems/faraday-0.8.7/lib/faraday/utils.rb:208:in `block in parse_nested_query'
    from /Users/myron/code/vanguard/bundle/ruby/1.9.1/gems/faraday-0.8.7/lib/faraday/utils.rb:206:in `each'
    from /Users/myron/code/vanguard/bundle/ruby/1.9.1/gems/faraday-0.8.7/lib/faraday/utils.rb:206:in `parse_nested_query'
    from /Users/myron/code/vanguard/bundle/ruby/1.9.1/gems/faraday-0.8.7/lib/faraday/utils.rb:129:in `merge_query'
    from /Users/myron/code/vanguard/bundle/ruby/1.9.1/gems/faraday-0.8.7/lib/faraday/request.rb:63:in `url'
    from /Users/myron/code/vanguard/bundle/ruby/1.9.1/gems/faraday-0.8.7/lib/faraday/connection.rb:240:in `block in run_request'
    from /Users/myron/code/vanguard/bundle/ruby/1.9.1/gems/faraday-0.8.7/lib/faraday/connection.rb:258:in `block in build_request'
    from /Users/myron/code/vanguard/bundle/ruby/1.9.1/gems/faraday-0.8.7/lib/faraday/request.rb:35:in `block in create'
    from /Users/myron/code/vanguard/bundle/ruby/1.9.1/gems/faraday-0.8.7/lib/faraday/request.rb:34:in `tap'
    from /Users/myron/code/vanguard/bundle/ruby/1.9.1/gems/faraday-0.8.7/lib/faraday/request.rb:34:in `create'
    from /Users/myron/code/vanguard/bundle/ruby/1.9.1/gems/faraday-0.8.7/lib/faraday/connection.rb:254:in `build_request'
    from /Users/myron/code/vanguard/bundle/ruby/1.9.1/gems/faraday-0.8.7/lib/faraday/connection.rb:239:in `run_request'
    from /Users/myron/code/vanguard/bundle/ruby/1.9.1/gems/faraday-0.8.7/lib/faraday/connection.rb:100:in `get'
    from /Users/myron/code/vanguard/bundle/ruby/1.9.1/gems/faraday-0.8.7/lib/faraday.rb:24:in `method_missing'
    from (irb):2
    from /Users/myron/.rvm/rubies/ruby-1.9.3-p327/bin/irb:16:in `<main>'
1.9.3p327 :003 > Faraday.get("http://www.travelocity.com/Promotions/0,,TRAVELOCITY|5911|hotels_motels,00.html")
URI::InvalidURIError: bad URI(is not URI?): http://www.travelocity.com/Promotions/0,,TRAVELOCITY|5911|hotels_motels,00.html
    from /Users/myron/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/uri/generic.rb:1202:in `rescue in merge'
    from /Users/myron/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/uri/generic.rb:1199:in `merge'
    from /Users/myron/code/vanguard/bundle/ruby/1.9.1/gems/faraday-0.8.7/lib/faraday/connection.rb:297:in `build_exclusive_url'
    from /Users/myron/code/vanguard/bundle/ruby/1.9.1/gems/faraday-0.8.7/lib/faraday/request.rb:94:in `to_env'
    from /Users/myron/code/vanguard/bundle/ruby/1.9.1/gems/faraday-0.8.7/lib/faraday/connection.rb:246:in `run_request'
    from /Users/myron/code/vanguard/bundle/ruby/1.9.1/gems/faraday-0.8.7/lib/faraday/connection.rb:100:in `get'
    from /Users/myron/code/vanguard/bundle/ruby/1.9.1/gems/faraday-0.8.7/lib/faraday.rb:24:in `method_missing'
    from (irb):3
    from /Users/myron/.rvm/rubies/ruby-1.9.3-p327/bin/irb:16:in `<main>'
```

Other HTTP clients like Typhoeus can handle these just fine:

```
1.9.3p327 :008 > Typhoeus.get("http://www.associatedasset.com/homeowner-resources/?Agritopia%A0Residential%A0Neighborhood%A0Owners%A0Association%2C%A0Inc.&ID=8").response_code
 => 200
1.9.3p327 :009 > Typhoeus.get("http://www.travelocity.com/Promotions/0,,TRAVELOCITY|5911|hotels_motels,00.html").response_code
 => 200
```

**Comment by andirayo** [comment]
Will this problem be fixed anytime soon?

It seems to me that Faraday is currently (version 0.9.1) unable to deal with non-UTF8 (but completely valid) URLs...
Example URL:
http://www.jijbent.nl/history.php?username=andr%E8&start=0&sort=datum&type=&orderby=DESC&game=4+op+een+rij

There are heaps of webservers out there that en- and decode URLs with 1-byte-encodings, like for example ISO-8859-1 (or -15), instead of UTF-8.

If you try to get the contents of such a URL, Faraday will first decode the URL parameters (why?) and then re-encode them. However, for the encoding process Faraday expects the parameters (and their values) to be valid UTF-8... Why?
Everything after the domain (including the GET-parameters) is by definition of HTTP just a byte-sequence and the webserver can decide what the byte-sequence means and, to be more precise for this example, can decide what character encoding to use to encode non-ASCii-characters.
That is btw, why non-ASCii characters in URL are NOT encoded with some Unicode-encoding but rather with Byte-encoding, as, for the HTTP-client it is unclear what the webserver will make out of the byte-sequence (also known as path).

The Faraday would be fine if it would not check for valid UTF-8. Why does it do that?

**Comment by mislav** [comment]
> Faraday will first decode the URL parameters (why?)

Because Faraday allows you to specify extra URL parameters for individual requests, and those get merged with URL parameters from the original request (decoded).

> for the encoding process Faraday expects the parameters (and their values) to be valid UTF-8... Why?

Because that's the only encoding strategy that we knew how to implement for now, and most people use UTF-8. If someone has an idea how to support different encodings for everyone, I would love a pull request! In the meantime, users can customize the `params_encoder` object with an encoding/decoding implementation of their choice.

> The Faraday would be fine if it would not check for valid UTF-8. Why does it do that?

It doesn't do that on purpose, but we just assume that UTF-8 is the default because we can't really know which was the original encoding of keys & values, since URLs don't carry this information.

We welcome concrete suggestions on how to make our URL params encoding/decoding scheme more agnostic to encodings.

**Comment by lithp** [comment]
I'm running into an issue where I need to send an exact url (it's signed). Is there any way to disable the parsing altogether?

**Comment by iMacTia** [comment]
Closing following @mislav explanation and with the same reason covered [here](https://github.com/lostisland/faraday/pull/513#issuecomment-254794047)
