### ISSUE TITLE
No method for OPTIONS HTTP verb

### ISSUE THREAD

**Issue by gjtorikian** [lostisland/faraday#305]
Shouldn't it be included in this array?

https://github.com/lostisland/faraday/blob/master/lib/faraday/connection.rb#L137

**Comment by nhocki** [comment]
I am terribly sorry to _bump_ this, but any agreement on supporting `options` as a method for `OPTIONS` requests? I'd be more than happy to submit a pull request to make this happen.

**Comment by mislav** [comment]
I'm still not sold on the idea. What would the current `options` method be called then?

Other methods that we support are verbs: get, post, put, delete. It makes it easy to understand that some action is happening when you call them. `options` wouldn't be a verb and as such I don't think it would make a nice shorthand method. If people are using `options` a ton in day-to-day code and can't bear to use `run_request` for some reason (I'd like to hear that reason!) then I would suggest naming the new method `http_options` to indicate that this is a HTTP request method.

**Comment by nhocki** [comment]
The argument of "the other methods are verbs" should not matter. They are not methods in Faraday because they are verbs, those method exist because they are HTTP methods. The same should happen for `options` IMO.




If this is the reason for not having `options`, then `head` should not be defined, as "head" in HTTP is not about "going", the verb.




I totally get the concern about breaking the API with `options`, but it's a big surprise that it is not "supported". It's way more consistent to have all HTTP methods handled the same.




And about not using `run_request`, like it was pointed before, the code without it is much much cleaner.




It's still your call (obviously :-) ) to decide to support this or not, but I'd love to change your mind about it, and if it's not going to be supported, that it's for something else other than "_options_ is not a verb". 



--
Nicolás Hock Isaza

**Comment by bithavoc** [comment]
+1 @nhocki

**Comment by dwo** [comment]
This caught me by surprise today. All of the examples with `conn.get`, `conn.post`, `conn.delete` etc. lead me to believe the obvious way to do an OPTIONS request was `conn.options`. 

Perhaps we could document this inconsistency and its `run_request` workaround in the `Faraday::Connection` rdocs or the README? I'm happy to compose a pull request.

**Comment by guyisra** [comment]
+1

Why isn't options the same as GET, POST, DELETE?

**Comment by iMacTia** [comment]
Even though I personally agree with @mislav, I can't ignore @sferik opinion and the community feedback. I checked the code and noticed that `options` is simply an `attr_reader`, plus it's being used mainly by tests.
However, we're talking about a public API that could potentially break some implementations being changed, hence this will be addressed only in Faraday 1.0

**Comment by erik-escobedo** [comment]
I think `conn.options` should totally be a thing. It's existence is heavily by the existence of `conn.get`,  `conn.post`, etc. But since it would break backwards compatibility, v1.0 sounds like a nice target to put this into.

**Comment by technoweenie** [comment]
Good news, everyone! I implemented this by overloading `#options` to support the new behavior, while maintaining the existing behavior. https://github.com/lostisland/faraday/pull/857
