### ISSUE TITLE
Inheritance and ParamsEncoders

### ISSUE THREAD

**Issue by jurriaan** [lostisland/faraday#336]
I needed a small change to the ParamsEncoder and saw it was implemented using modules. Is it possible for you to change this to use classes? 
Right now I have to copy the content of the FlatParamsEncoder to my own ParamsEncoder and make the change in there. I think it should be possible to do so without having to copy everything.

What do you think?

**Comment by mislav** [comment]
Not right now, sorry. If you need to specify your own encoder/decoder, you need to copy entire contents and make tweaks. The problem with subclassing is that we would have to change the current implementation to break it down into overridable methods, which might be a lot of work, and then commit to keeping compatibility with those methods in future Faraday versions because people like you will be subclassing them and overriding parts of functionality. That's a lot of extra responsibility that I can't take on right now.
