### ISSUE TITLE
thread safety

### ISSUE THREAD

**Issue by ABorovenskiy** [lostisland/faraday#370]
After reading some old issues in the repository, I've found out that faraday is thread safe.

Would be nice if you add corresponding comment to the README file.

**Comment by mislav** [comment]
By all means, please use Faraday in a multithreaded environment and report your findings. However, no automated tests exist that validate the claim that Faraday is perfectly thread safe. Until then, we won't have such notice in the README.

Generally, I just assume Ruby libraries are thread-safe until proven otherwise.
