### ISSUE TITLE
token auth newline with passenger standalone

### ISSUE THREAD

**Issue by madaray** [lostisland/faraday#372]
v0.9.0 /lib/faraday/request/authorization.rb line 20 adds a newline between options 

which works fine on localhost but using nginx it does not. This is from the rails request in the API app - Phusion Passenger version 4.0.41: 

"HTTP_AUTHORIZATION"=>"Token token=\"<token>\",", "HTTP_USER_AGENT"=>"Faraday v0.9.0"

the data after the comma is missing.

This is from the localhost - Thin web server (v1.6.2 codename Doc Brown):

"HTTP_AUTHORIZATION"=>"Token token=\"<token>\",\n                     option_1=\"<option_1_value>\"", "HTTP_USER_AGENT"=>"Faraday v0.9.0"

monkey patching faraday to not use \n fixes the problem. Rails doesn't add the newline when working with ActionController::HttpAuthentication::Token.encode_credentials:

"Token token=\"<token>\", option_1=\"<option_1_value>\"

So I assume that removing it would not make the header invalid?

**Comment by cavi21** [comment]
Hi there! probably I missed something but why this is closed? that `\n` in the **[#build_hash](https://github.com/lostisland/faraday/blob/master/lib/faraday/request/authorization.rb#L20)** method is causing issue between different setups on different servers and not sure the need of it?

Does anyone have any idea why is there? happy to open a PR if it's need it

Have a great day!

**Comment by iMacTia** [comment]
Hi @cavi21, I'm sorry this issue was not addressed before. I suppose @madaray closed it because no one replied in more than 2 years.
I've recently started contributing to Faraday and I'm now trying to address issues more quickly.

That said, I can see the issue here and I agree that headers should not contain any "\n" as that will be read as the end of the header value.
I think the author of that code was just trying to make it more user-friendly to read.

That said, I could review a PR that removes the newlines making all tests still passing.

We have a release (v0.11.0) scheduled for tomorrow, compatibly with your time I could merge this is in time for it.

Please mention this Issue (which I'll now reopen) in your PR

**Comment by cavi21** [comment]
Awesome news @iMacTia I'll open a PR as you said and we will go from there!

Thanks for the prompt reply on this!
