### ISSUE TITLE
"RuntimeError: :httpclient is not registered on Faraday::Adapter" with elasticsearch-rails gem

### ISSUE THREAD

**Issue by ralphamale** [lostisland/faraday#383]
I'm trying to integrate elasticsearch into my Rails app and did the following, as their instructions stated:

In my Gemfile:

```
gem "elasticsearch", git: "git://github.com/elasticsearch/elasticsearch-ruby.git"
gem "elasticsearch-model", git: "git://github.com/elasticsearch/elasticsearch-rails.git"
gem "elasticsearch-rails", git: "git://github.com/elasticsearch/elasticsearch-rails.git"
```

And in my design.rb file (the model I want to search through):

```
class Design < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
```

I have tried it locally and on Heroku to run

```
Design.import
```

and it results in the error:

```
RuntimeError: :httpclient is not registered on Faraday::Adapter
from /Users/me/.rvm/gems/ruby-1.9.3-p484@teepublic/gems/faraday-0.8.4/lib/faraday.rb:64:in `lookup_middleware'
```

I tried contacting Bonsai and Elasticsearch and they said that this was a problem with the way Faraday was being implemented. Can anyone help me figure out why this error is occurring?

**Comment by kalashnikovisme** [comment]
Have the same error with faraday 2.5.2 and elasticsearch-rails 7.2.1

**Comment by iMacTia** [comment]
@kalashnikovisme I checked `elasticsearch-rails` codebase and there's no reference to Faraday. I suspect this is coming from some downstream dependency.
In order to identify a proper fix, I'd need to see the stacktrace of the error, however I'm pretty sure this can be fixed by adding `faraday-httpclient` to your Gemfile.

I'd also suggest you to open a new issue as your problem is most probably unrelated from this 8 years-old one despite the error message being the same 😄

**Comment by kalashnikovisme** [comment]
@iMacTia thanks) will try fix with adding `faraday-httpclient`)

Haven't figured out that it's too old issue)

**Comment by kalashnikovisme** [comment]
Bug was fixed with adding `faraday-httpclient`! Thnx!

**Comment by henriquesml** [comment]
Add the `faraday-httpclient` gem works for me. Thanks!
