### ISSUE TITLE
Faraday::ConnectionFailed is thrown when the timeout set on Faraday stops the request.

### ISSUE THREAD

**Issue by antoine-lizee** [lostisland/faraday#488]
Something like:
```
response = connection.get do |request|
  request.url "/CEAPI/getContext"
  request.params[KEY1] = "Something"
  request.options.timeout = 5
  request.options.open_timeout = 2
end
```

will throw: `Faraday::ConnectionFailed: execution expired` when the dns of the base url of the `connection` is resolvable to a server down. I would have expected a `Faraday::TimeoutError` since this is the `request.options.timeout` from Faraday which stops the request from hanging.

**Comment by kennethkalmer** [comment]
I think `ConnectionFailed` is the correct exception here. Whether the name resolved, or used a lookup from `/etc/hosts` or connecting directly to an API address, the fact here is that the connection _failed_. `TimeoutError` is for when a connection was/is successfully established but no data is flowing over the connection anymore.

In your snippet above, `request.options.open_timeout` is probably what is triggering the `Faraday::ConnectionFailed` exception...

HTH

**Comment by antoine-lizee** [comment]
All right, makes sense, thanks for the answer. 
It's not super documented though, so I'm glad it's here now :-).

Before I close this issue, just a last question. It seems that the default request has no timeout? Is there any rationale for this?

**Comment by kennethkalmer** [comment]
Because a default would be arbitrary... In the end it is up to your Ruby runtime's default network timeout, which I believe is 2 minutes on MRI.

Maybe a different backend could have their own defaults, but in the real world it makes no sense otherwise... In reality you need to measure your own patterns and set timeouts accordingly. I did a [presentation](https://speakerdeck.com/kennethkalmer/broken-dreams-and-shattered-promises?slide=13) earlier this year on this exact topic of instrumenting API calls, and I have some examples to share on how wildly different the performance characteristics can be.

HTH

**Comment by antoine-lizee** [comment]
I understand that it would be arbitrary, that's why I would put something pretty high (and document it). The theoretical point of view you're taking is convincing too, though. Thanks.
