### ISSUE TITLE
making a post on a connection using a block to set request options doesn't work as intended

### ISSUE THREAD

**Issue by nikhilvallishayee** [lostisland/faraday#495]
I have current code  

``` rb
@conn = Faraday.new(:url => Settings.cleartrip_extranet_endpoint ) do |faraday|
      faraday.response :logger                  # log requests to STDOUT
      faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
      faraday.headers['Content-Type'] = 'application/xml'
      faraday.headers['content-type'] = 'application/xml'
      faraday.headers['X-CT-SOURCETYPE'] = 'API'
      faraday.headers['X-CT-API-KEY'] = Settings.cleartrip_extranet_key
    end
  end
```

to set up the initialization

and the following code to make the call:

``` rb
@conn.post do |req|
      req.url '/hotel-room-rate'
      req.headers['Content-Type'] = 'application/xml'
      req.body = payload
    end
```

the body is going empty and the url doesn't have 'hotel-room-rate' appended.

On the other hand,
 @conn.post '/hotel-room-rate', payload 
works fine.
So, the issue is definitely with passing options in the block.

**Comment by mislav** [comment]
Hi, I couldn't replicate your problem. For me, the URL will end in `/hotel-room-rate` and the POST body will be equal to `payload`. Can you ensure you are running latest Faraday version?

**Comment by chris** [comment]
I believe I may be running into the same issue. What I've found is that I get an empty POST body unless I use the `:net_http` adapter - if I use typhoeus or httpclient as the adapter, it doesn't seem to form my request properly. I'm using regular form encoded body (so not specifying a different content type, etc.). I've tried explicitly setting the content type, which doesn't seem to help. Identical code otherwise, all I'm doing is changing the adapter, and then I get a failure.

**Comment by stephankaag** [comment]
Same here!

**Comment by iMacTia** [comment]
Hi guys,
I don't think we can help without having a clear run-to-reproduce code example.
The one provided by @nikhilvallishayee doesn't look to reproduce the issue (and is also filled with `Settings` values that we don't have access to).
Happy to try helping out if given some failing examples

**Comment by iMacTia** [comment]
Closing for not being able to reproduce, happy to reopen if provided with a code example.
