### ISSUE TITLE
v0.9.2 empty params handled differently than v0.9.1

### ISSUE THREAD

**Issue by zaadjis** [lostisland/faraday#533]
Looks like f78d51da broke BC for us. We have middleware that's used for request signing, which broke when upgrading to v0.9.2 because param serialization changed. Probably should move that commit to a major release (if Faraday follows SemVer).

**Comment by mislav** [comment]
I'm sorry. What is BC?

This wasn't just a feature change; it was a bug. Some people would initialize their connection with a base URI like `example.com/?a` and expect that it gets preserved. However, the `a` would get turned into `a=` when a request got sent, effectively not respecting what they initialized the connection with. Therefore, I wanted to fix this, since the old behavior was a bug.

Is it an option for you to amend your request signing middleware?

**Comment by zaadjis** [comment]
BC = backward compatibility

Seem that bugfix is "inconsistent": when I set a query param "a" to `nil` (url query = "?a") and then parse that url query with Faraday::Utils.parse, the "a" param ends up as `true` (not `nil` or `""`). I guess Utils.parse needs to be modified to be consistent with that bugfix.

Feel free to close (I can amend my stuff). I submitted this issue mostly to complain that my stuff broke after a PATCH release (0.9.1->0.9.2) :)

**Comment by mislav** [comment]
One the contrary: `a` in query without the equals sign is parsed as `nil`.

Observe the bug that was fixed here:

```rb
# before:
Faraday.new("http://example.com/?a").build_url("/foo", b: "1") #=> http://example.com/foo?a=&b=1

# after:
Faraday.new("http://example.com/?a").build_url("/foo", b: "1") #=> http://example.com/foo?a&b=1
```

**Comment by zaadjis** [comment]
I'm probably bad at explaining my issue. Basically what broke my code is this change:

```rb
# v0.9.1
Faraday::Utils.parse_query Faraday.new("http://example.com/?a").build_url("/foo", b: "1").query
# => {"a"=>"", "b"=>"1"}

# v0.9.2
Faraday::Utils.parse_query Faraday.new("http://example.com/?a").build_url("/foo", b: "1").query
# => {"a"=>true, "b"=>"1"}
```

Note that "a" changed from `""` to `true`. So wht I'm saying is that  f78d51d should have been in a MAJOR release OR also changed `Faraday::Utils.parse_query` to handle "empty" params as before.

**Comment by baburdick** [comment]
+1

**Comment by mislav** [comment]
Oh, I can see now where you're getting `true` from. You're using `parse_query` on the end result. That method uses the "flat" params parser strategy which didn't change since v0.9.0, but does have a different approach at handling blank values than the default "nested" strategy used within `build_url()`.

I can definitely see how your app broke, but please understand that the old behavior was still a bug and your code simply relied on a bug. Furthermore, for your code signing approach you used `parse_query` which treats parameters differently than the default encoder. You should have used `parse_nested_query`, or better yet: you shouldn't have parsed a query at all, but just signed the request by splitting the query params string at `&`, sorting the array, and calculating a checksum for that. No params parsing needed.

I can't fix your use-case without bringing back the old bug. Please understand that your usage wasn't typical for Faraday everyday use. People mostly won't parse any query strings manually.

**Comment by zaadjis** [comment]
> your code simply relied on a bug

I see, thanks.

> you shouldn't have parsed a query at all

I wish I wouldn't need to (params need to be encoded in a special way before signing), but Env (passed to middlewares) doesn't have `params` in their original (unescaped) form.

**Comment by mislav** [comment]
I recommend using `parse_nested_query()` instead of `parse_query()` because the former is default parser mode otherwise within Faraday.
