### ISSUE TITLE
Drop support for ruby 1.8?

### ISSUE THREAD

**Issue by MidnightWonderer** [lostisland/faraday#553]
Hi, I wonder when or what condition that will make faraday drop support for ruby 1.8.
It will get harder to move forward as the tests is failing simply because bundler can not install dependency gem. ([example](https://travis-ci.org/lostisland/faraday/builds/98350202))
  
You have something in mind or waiting for some condition or signal before dropping support?

**Comment by mislav** [comment]
Thanks for letting me know about the failure. Fixed in master by downgrading addressable.

We won't drop 1.8 compatibility yet because we don't get anything from it. We didn't plan to use Ruby 1.9-specific features anytime soon. For the next big release, dropping 1.8 is definitely an option; but for now, it says.
