### ISSUE TITLE
Project abandoned? New maintainers needed?

### ISSUE THREAD

**Issue by sbleon** [lostisland/faraday#567]
Hi, all. I'm writing to express my concern about the health of this awesome project. There have been no commits made (on any branch) in three months. There is getting to be a large backlog of PRs and open issues. Do the maintainers need more help?

I'd be willing to put in some time to help to review the backlogs, but I don't really want to spend my time on it if nothing will be merged.

PS. 1,000 commits is a nice round number, but that's really not a good reason to freeze the project forever ;-) 

![screen shot 2016-03-22 at 4 14 34 pm](https://cloud.githubusercontent.com/assets/198711/13966525/36c0f4d4-f049-11e5-8af2-0fce17219431.png)

**Comment by technoweenie** [comment]
What are your goals with Faraday? Do you just want to use it in a new project? Are you already using it, and just want to post and merge some bug fixes and small gem releases? 

As a user, I'd recommend looking into other, more actively maintained options. The only one I know of is http://httpirb.com/. I have no experience with it, however.

In the past, I've been pretty liberal with push access (that's actually why this repository is in an org and not my personal account). I wouldn't mind giving you access to merge fixes. I just don't have the time or interest to work on Faraday right now. Giving you access means I'll still have to review PRs and push out good releases to existing Faraday users.

**Comment by mislav** [comment]
Thanks for your interest, @sbleon, and sorry for the late reply.

We haven't been maintaining Faraday as aggressively as before because technoweenie has moved on to other interests, and I had faith in Faraday being stable enough that it can remain unchanged for a while. Just because it didn't have commits for a while, it doesn't mean that the project is "dead". I think that a project can only be dead when it only sees negligible usage, and Faraday is far from that. The latest version has seen almost 5 million gem downloads since October.

There are definitely interesting issues and good PRs in the backlog, but not all are necessarily actionable or a good idea for the project right now. The fact they are there and still open just means that I haven't completely dismissed them yet (it takes time to reach a decision). As for my thoughts about how people can contribute to a project and what are some challenges of maintaining, [please read here](https://github.com/lostisland/faraday/issues/550#issuecomment-163586075).

I'd welcome any casual help with triaging the big backlog that we have. For instance, reviewing the PRs for 3 things:

1. Does the feature make sense for the spirit of Faraday? Maintainers will have to own it for years to come.
2. Does the code look OK? If it affects one adapter, does it bring the same functionality across all other adapters?
3. Does it have proper tests? This is the most common blocker.

**Comment by technoweenie** [comment]
Thanks for chiming in, @mislav :)

**Comment by sbleon** [comment]
Thanks for the feedback, guys! I'll see what I can do to help winnow down the backlog, with @mislav's guidelines in mind.
