### ISSUE TITLE
Cannot set headers on RequestOptions

### ISSUE THREAD

**Issue by emirkin** [lostisland/faraday#573]
If you do

```
Faraday.new(...).get(url, params) do |req|
   req.options.merge!(request_headers: ...)
end
```

 you will get an error _"RequestOptions does not have 'request_headers=' method"_, whereas `req.headers.merge!(...)` works fine.

Isn't the purpose of `RequestOptions::options::merge!` to allow for setting the headers too (alongside `:params_encoder, :proxy, :bind, :timeout, :open_timeout, :boundary, :oauth`)?

**Comment by emirkin** [comment]
Worth mentioning is that if I do `Faraday.new(...).get(url, request_headers: ...)` instead (pass headers to Faraday earlier in the pipeline), I do get my desired headers (I used `request_headers: {'cache-control' => 'no-cache'}` in the HTTP request but I also see them inserted in the query portion of the url.

**Comment by iMacTia** [comment]
Hi @emirkin. The reason for this strange behaviour is easy to explain.
When you pass `request_headers` as an option in the Faraday initialiser or `#get` method (second case) you're setting a value to `env[:request_headers]`.
When calling `req.options.request_headers` through the `merge!`, instead, in reality you're accessing `env[:request][:request_headers]`.

I understand this can be confusing, but that's where request headers are stored, outside of the request options.

Now, the strange bit is that you see them in the query portion of the URL. That shouldn't happen at all as they are headers, not parameters.

I would like to see a code example that replicates this issue on the net_http adapter.
This is because `TyphoeusAdapter` have not been maintained (we're in the process of removing it)
