### ISSUE TITLE
How to set basic auth on a per-request basis?

### ISSUE THREAD

**Issue by aviflax** [lostisland/faraday#605]
I am using a single instance of Faraday to make requests to various services; each requires a discrete set of credentials, so I’d like to set the basic auth credentials on a request-by-request basis. I searched the docs, code, and issues, but every example I found showed setting the credentials at the client/connection level, rather than at the request level. For now I can just “manually” set the header with a “manually” generated value, and that’s no big deal, but it’d be cleaner to use a specific API. Does Faraday have some facility for this?

Thank you!
Avi

**Comment by iMacTia** [comment]
Hi @aviflax,

I don't have a computer with me so I can't dig the code to look how to do that, but as a general advice it would be much better to instanciate a different Faraday object for each service you need to connect to.
I understand your application can be really small or still at an embrionale state, but is generally a poor design choice to call different API with the same instance.

If you have some shared logics and you don't want to copy-and-paste code around here are a couple of advices:

1.  create an helper method that instanciate a new Faraday connection with a service configuration (URL, basic auth, etc)
2. Even better, create a small wrapper class for each service (maybe a singleton?) which will instanciate and retain a different Faraday connection instance (with different configs). If there are many shared logics, add a superclass to share them and keep being DRY.

If you still think the above are not applicable on your case, please share some additional detail and next week (with a computer!) I'lol try to help 😊

**Comment by aviflax** [comment]
Hi @iMacTia thank you so much for the thorough reply! I really appreciate it.

> as a general advice it would be much better to instanciate a different Faraday object for each service you need to connect to… is generally a poor design choice to call different API with the same instance.

This is good to know — can you elaborate on the reason for this? I’ve been writing Web service clients for many years and in many languages, and I’ve found that every HTTP client library has its own perspective on this sort of thing.

My own inclination is to view an instance of a client as a sort of “template” for sending some set of requests that have something in common — maybe they have much in common, or maybe just a little. But that’s the conceptual framework I usually apply.

In the case of my system, I’m making requests to dozens of different _instances_ of the _same_ API. The only thing that really varies is the host name and the credentials. So that’s what I thought I’d vary with each individual request, rather than at the client instance level.

That said, I’m perfectly willing to accept that my usual approach might be ill-fitting for Faraday. Perhaps with Faraday, each instance is only intended to ever interact with a single host? Perhaps this is important for things like persistent connections? (I am using the `:net_http_persistent` adapter.) I’d just love to gain deeper insight into this, I think it’ll help me build a deeper understanding of how to _really_ use Faraday well.

Thank you!

**Comment by iMacTia** [comment]
Hi @aviflax,

I said "usually" specifically because I know nothing about the services you're using so I'm not saying you're doing it wrong (I'm happy it looks like you got this), just trying to make you consider a different approach before trying tricky things with Faraday :)

So, in the generic case and especially in the Faraday case, it is a good practice to split the call to services into different instances for many different reasons, I'll list some of them here and I understand they can be argued so you don't need to agree with all of them:

1. Code organisation: different API/Services are usually split for a reason (context, usage, ...) so having the same organisation client-side helps to make the code easier to understand and to maintain.

2. Asynchronous calls / Parallelism: not sure is your case (maybe could in the future), but if you want to make asynchronous/parallel calls sharing the same connection instance can bring to unwanted errors (instance variables conflicts for example, or any other shared/concurrent resource)

3. Maintainability: even though API/Services are really similar today, they could be different in the future. For example, some of them could change the authentication process or change the way you send parameters, or request any special behaviour (add always the same parameter to the request, add a specific header, and so on). Having your code separated for each of them allows you to manage all of this without filling your code with if-then-else.

From my understanding, the API you're calling is spilt into different services (a.k.a. "Endpoints", typical of .NET framework), so you could have something like the "Users service", the "Transactions service", and so on.

If that's the case, then code could be organised like:

```ruby
class UsersService
  def self.connection
    @conn ||= Faraday.new ...
  end

  def find(id)
    @conn.get ...
  end
end
```

Apologies for the short example, but writing from my mobile doesn't really help :D 
Of course you'll have a similar `TransactionService` class, and in case they share logics (for example the connection middlewares, you can create a superclass from which they both inherit.
For example, they share basic auth, so you can define user and pass as class config (constant or variable) and use then to initialise the connection in the superclass.

Again, apologies for the shortage of code, I hope this makes some sense or at least can be a starting point to refactor your code in a Faraday-compatible way ^_^

**Comment by aviflax** [comment]
@iMacTia sorry for the delay in my response. I appreciate you taking the time to thoughtfully and thoroughly address my concerns. I think we never managed to quite get on the same page as to the use case I’m dealing with, but that’s OK — it’s pretty clear that Faraday’s not meant to be used the way that I’d prefer to use it. So that’s fine; I’ll adapt.

Thanks again!
