### ISSUE TITLE
Connection reset by peer - SSL_connect

### ISSUE THREAD

**Issue by rusikf** [lostisland/faraday#606]
Hello ruby hackers!

I am using koala gem, which uses faraday internally, and some time I get this error: 
`Faraday::ConnectionFailed
Connection reset by peer - SSL_connect`

 In what can be a problem ? It looks the facebook graph api use tls, how to force it in faraday?

**Comment by iMacTia** [comment]
Hi @rusikf, thanks for opening this issue!

The error looks like something unrelated with Faraday and due to the connection between client and API. I've seen you opened an issue in koala as well (https://github.com/arsduo/koala/issues/544), good spot. And reading the replies you got so far, it looks like a common issue on that side.

I'm going to close this issue for the meantime assuming it is due to koala rather than Faraday and give some time to investigate your issue on koala projects.

If, by any mean, you find that the issue lie inside Faraday, feel free to reopen or create a new issue here and we'll see what we can do.
