### ISSUE TITLE
Remove the legacy Typhoeus adapter

### ISSUE THREAD

**Issue by PragTob** [lostisland/faraday#608]
edit: see discussions, basically the adapter is old and you need to load the one from typhoeus

For all that I can tell Faraday has gotten incompatible with new typhoeus/ethon versions (our particular combination was 0.8 and 0.9, respectively)

The concrete error was:

```
ETHON: Libcurl initialized

[Ethon::Errors::InvalidOption] The option: disable_ssl_peer_verification is invalid.
Please try ssl_verifypeer instead of disable_ssl_peer_verification. ({:scheme=>"http", :user=>nil, :password=>nil, :host=>"localhost", :path=>"", :port=>9200, :protocol=>"http"})
Ethon::Errors::InvalidOption: The option: disable_ssl_peer_verification is invalid.
Please try ssl_verifypeer instead of disable_ssl_peer_verification.
from /some_direcctory/gems/ethon-0.9.0/lib/ethon/easy.rb:238:in `block in set_attributes'
```

The offending code is here in the [typhoeus adapter](https://github.com/lostisland/faraday/blob/3e5e1dd5af8b3c1e195ce04ea98630b221bb17c5/lib/faraday/adapter/typhoeus.rb#L39-L43):

``` ruby
        req = ::Typhoeus::Request.new env[:url].to_s,
          :method  => method,
          :body    => env[:body],
          :headers => env[:request_headers],
          :disable_ssl_peer_verification => (env[:ssl] && env[:ssl].disable?)
```

Thanks for making faraday!

**Comment by mislav** [comment]
The Typhoeus adapter shipping with Faraday was only ever [compatible with ancient Typhoeus version 0.3](https://github.com/lostisland/faraday/blob/3e5e1dd5af8b3c1e195ce04ea98630b221bb17c5/Gemfile#L22). Subsequent versions of Typhoeus ship with their own Faraday adapter and it was their responsibility to ship a compatible adapter. That's why we stopped maintaining the Typhoeus adapter within Faraday core.

If there is a problem with the adapter, first make sure that the [adapter is loaded from Typhoeus own code](https://github.com/typhoeus/typhoeus/blob/181834e2483d392d0f7ab0cd17f544cd252c7b2f/lib/typhoeus/adapters/faraday.rb#L9-L15), and then if there's still a problem, report it to their repo.

**Comment by PragTob** [comment]
@mislav thanks for the hint didn't know that, in this case I think it'd be good to remove the ancient adapter :)

**Comment by mislav** [comment]
> I think it'd be good to remove the ancient adapter :)

I think so too, to reduce confusion. Perhaps you can rename your issue to something like "Remove the legacy Typhoeus adapter" and we'll keep it open as a todo item for the next release. 😉

**Comment by PragTob** [comment]
WIll do, thanks a lot for the quick feedback and help! :heart:

**Comment by philsturgeon** [comment]
+1 for this one. After noticing https://github.com/lostisland/faraday/issues/612 we're jumping ship on NetHTTP until our apps are all on Ruby 2.5.0, and trying to use this has lead to some confusion.

Requiring specifically the right one solves the problem, but you really should start ditching old core ones, especially for those that have their own. Also, it should go on the README :) 

```
require 'typhoeus'
require 'typhoeus/adapters/faraday'
```

**Comment by iMacTia** [comment]
@philsturgeon Fortunately we already have @olleolleolle taking care of this in #715.
I'm sure he'll welcome your suggestion on making it clearer on the README how to use the external adapter

**Comment by philsturgeon** [comment]
Done! https://github.com/lostisland/faraday/pull/740
