### ISSUE TITLE
Docs for retry_if are incorrect

### ISSUE THREAD

**Issue by latortuga** [lostisland/faraday#609]
Docs for `retry_if` indicate that it is used independent of retry count:
```ruby
    # retry_if            - block that will receive the env object and the exception raised
    #                       and should decide if the code should retry still the action or
    #                       not independent of the retry count. This would be useful
    #                       if the exception produced is non-recoverable or if the
    #                       the HTTP method called is not idempotent.
```

But [the code](https://github.com/lostisland/faraday/blob/master/lib/faraday/request/retry.rb#L118) indicates otherwise. One or the other should be fixed, I don't really have an opinion either way.

**Comment by iMacTia** [comment]
Hi @latortuga, thanks for opening this issue.
I didn't write the code, but I really think this is just a misunderstanding/poor description in the doc.
My interpretation of the doc is:

>  #                       block that will receive the env object and the exception raised
    #                       and should decide if the code should retry still the action or
    #                       not *even if the retry count have not been exceeded*. This would be useful
    #                       if the exception produced is non-recoverable or if the
    #                       the HTTP method called is not idempotent.

I'm not english mother-tongue so to be honest I'm not able to provide a better description, but please feel free to propose a PR if you think it's not clear.

**Comment by latortuga** [comment]
I agree that it could be a doc issue, but it's not clear to me one way or the other. This is how I see it:

```rugy
# current code
retries_remaining && (valid_retry_method || retry_if)

# option 1: how I think it ought to work
(retries_remaining && valid_retry_method) || retry_if

# option 2: alternative
valid_retry_method && (retries_remaining || retry_if)
```

Further, the docs state:

> This would be useful if the exception produced is non-recoverable or if the HTTP method called is not idempotent.

The _only_ way this can be the case is if `retry_if` is specified AND non-idempotent HTTP methods are configured; the latter is not specifically called out in the description and makes me suspect that options 1 or 2 above were the original intent.

**Comment by iMacTia** [comment]
Reading the `methods` documentation:

> A list of HTTP methods to retry without calling retry_if.
Pass an empty Array to call retry_if for all exceptions.
(defaults to the idempotent HTTP methods in IDEMPOTENT_METHODS).


So rather than reading it as `valid_retry_method`, try to read it as `method_you_can_retry_safely`.
Given it is idempotent, you can safely execute it again without even considering the `retry_if` callback.
This way, `methods` is simply there to optionally short-circuit the retry_if callback.
Which sum up nicely with the current code version:

```ruby
# current code:
retries_remaining && (idempotent_method || retry_if)
```

So the `independent of the retry count` ambiguous sentence is referring to the fact that `retry_if` callback can block the retries loop BEFORE the number of retries is exceeded. However, `retry_if` callback can be ignored for idempotent HTTP methods configured with `methods`.

Making it as a schema:

```
    Request is performed
    # Request successful?
    Y: do nothing
    N: # number of retries exceeded? (or no retry remaining?)
        Y: bubble-up exception and stop retrying
        N: # Is the HTTP method idempotent?
            Y: Retry the call
            N: Call "retry_if" block, is the result true?
                Y: Retry the call
                N: bubble-up exception and stop retrying
```

From what I can see and understand, documentation is describing the behaviour of the code and looks clear enough to me.
If you still think that the doc can be improved to describe it better, feel free to open a PR 😄

**Comment by latortuga** [comment]
This is a good explanation, thanks @iMacTia
