### ISSUE TITLE
HTTPClient adapter should set SSL timeout

### ISSUE THREAD

**Issue by dgolombek** [lostisland/faraday#622]
For reasons that I'm not clear on, HTTPClient on JRuby requires you to set SSL timeout differently than regular timeouts (and only has a singular timeout value, instead of different timeouts for connecting and reading/writing). I've asked about merging the timeouts, but until that's done, Faraday should set the ssl timeout separately.

**Comment by iMacTia** [comment]
Hi @dgolombek and thanks for opening this issue.
Before progressing with this I would like to have a better understanding of the situation.
From what I can see, the issue lies on HTTPClient storing the `timeout` and `ssl_timeout` into two separate variables.
On Faraday's HTTPClient adapter we only set the "normal" timeout, so when performing ssl (https) calls this gets ignored.
However, you already asked HTTPClient gem owner to merge the two timeouts on their side.
I can also see you have already opened an [issue](https://github.com/nahi/httpclient/issues/341) on their side.

By the look of it, I would be more inclined to wait for a fix on HTTPClient gem as I agree with you on this being an inconsistency on their side (the gem behaves differently based on the Ruby version).

I personally don't think having this temporary fixed on Faraday will be of any help, plus:

1. The solution in #623 is a bit dirty: it has to check if the instance responds to a given method that is only available with JRuby.
2. They will fix this at some time on their side, and we could forget this temporary fix inside Faraday. This wouldn't be the first time this happens, so I would rather prefer to avoid it.
3. Even though you get this fixed in faraday, I can't guarantee you a release date for it.

My suggestion at this point is to wait for an answer from HTTPClient gem owner and see what they want to do. If you're eager to get this fixed because you need it on your project, then best thing to do in this case is to monkey-patch either Faraday or the Client until a solution is merged.

**Comment by dgolombek** [comment]
I went back and forth before opening this bug, for the reasons you mention. I will say:

1. The ssl_config.timeout= method is available in both MRI and JRuby -- the respond_to? check is to handle the field possibly going away in the future. The field just isn't used in MRI
2. This problem will continue to hurt anyone who neglects to upgrade HTTPClient, which may take a while

In any case, I'm happy to wait to see the results of the discussion on nahi/httpclient#341 before making a decision either which way here -- it's certainly possibly that the maintainers have a rationale for the separate SSL timeout that I'm not aware of.

**Comment by iMacTia** [comment]
Agreed, there could be some implementation details we're missing that could explain this odd behaviour. I prefer to have everything clear before discussing on where the fix should be applied.

I subscribed to nahi/httpclient#341 to be sure I get notified when things are moving

**Comment by dgolombek** [comment]
@iMacTia, the owner of httpclient clarified that the ssl_config.timeout value is indeed a separate timeout. It's the timeout of the SSL session, not of the connection itself. Perhaps poorly named, but important. So my existing fix is wrong, since it shouldn't be set to the same value, but it's something that would be nice to allow users to set somehow (along with keep_alive_timeout).

**Comment by iMacTia** [comment]
Thanks for the investigation @dgolombek 👍 ! 
Happy to see you're already working with HTTPClient gem maintainers to get it fixed.

On the ssl_timeout thing, we want to avoid adding support for things on Faraday that are only supported by a subset of the adapters.
So unfortunately in this case I wouldn't be inclined in accepting a PR that allow users to set that value.

**Comment by dgolombek** [comment]
I understand that desire. How would you feel about a simple callback/hook mechanism, whereby the user could set a callback function in the adapter that would be called with each request. This would provide a cleaner mechanism for the caller to do adapter-specific work without monkeypatching the gem. I can submit that as a separate request if you think it sounds reasonable.

**Comment by iMacTia** [comment]
That not a bad idea at all and I can ensure you we've already discussed internally about it. Having some sort of `custom builder` that passes the adapter to a user-defined block would allow for any special configuration like this one.

Unfortunately, this is also breaking Faraday's main aim to be a standard, adapter-agnostic interface.
Trying to make a comparison with `ActiveRecord`, it would be like executing database specific queries supported only by one DB. That would solve your problem, sure, but you're loosing the ability of changing the database type effortlessly as you'll also need to track and change all this custom queries.

This is the main reason why this kind of feature is not currently available, but again this doesn't mean it won't be added in the future, once we get to an agreement internally.

**Comment by iMacTia** [comment]
Hi @dgolombek just a quick note that I'm working on that callback/hook mechanism that will allow you to set the `ssl_config.timeout`, see #651.
I've also included an example specifically for you in the PR description 😄

**Comment by dgolombek** [comment]
Thanks so much, that mechanism looks great. 

On a side note, I see that 0.10.1 made it through Travis, but hasn't made it's way to rubygems -- mind pushing it along? Thank you.

**Comment by iMacTia** [comment]
It's building on travis now 😉 
Will be automatically released if all tests are green 👍

**Comment by iMacTia** [comment]
Just a quick note to let you know that #651 has been merged and released with v0.11.0
