### ISSUE TITLE
Calling Faraday::Connection#adapter twice registers two adapters

### ISSUE THREAD

**Issue by mwpastore** [lostisland/faraday#631]
Hi folks,

I'm working with a library (Munson) that provides a method to configure Faraday, something like:

```ruby
def configure
  @faraday = Faraday.new do |conn|
    conn.adapter Faraday.default_adapter

    yield conn if block_given?
  end
end
```

I want to change the adapter, so I call the configure method like so:

```ruby
Munson.configure do |conn|
  conn.adapter :rack, MyApp.new
end
```

However, when this library calls out to Faraday, it's trying to use the default adapter instead of the Rack adapter. Inspecting the connection object, it looks like there are actually two adapters registered now:

```ruby
@faraday=#<Faraday::Connection:0x007fd7f2735498
  @parallel_manager=nil,
  @headers={"User-Agent"=>"Faraday v0.10.0"},
  @params={},
  @options=#<Faraday::RequestOptions (empty)>,
  @ssl=#<Faraday::SSLOptions (empty)>,
  @default_parallel_manager=nil,
  @builder=#<Faraday::RackBuilder:0x007fd7f2735268
    @handlers=[Faraday::Adapter::NetHttp, Faraday::Adapter::Rack, Munson::Middleware::EncodeJsonApi, Munson::Middleware::JsonParser]
  >, 
  @url_prefix=#<URI::HTTP http:/>, 
  @proxy=nil
>
```

Is this intentional? Is there a way to de-register an adapter, or replace the registered adapter?

**Comment by iMacTia** [comment]
Hi @mwpastore, unfortunately the answer is yes, this is intentional.
When you build the middlewares stack with the block initialiser in Faraday, you have to follow some simple rules:

1. Order matters: You should carefully choose the order of your middlewares as they'll be called in the same order as they're defined. If, for example, you have a middleware calculating the signature on your payload and after that another one adding stuff to your payload, then the signature will be incorrect as the former middleware will run BEFORE the latter.
2. Adapter at the end: the adapter MUST appear at the end of the stack and the reason is simple, it's the one that will perform the call, so every other middleware should be done by then (also response middlewares as they should use the async syntax (callback) to manage the response.
3. Only one adapter: this is because Faraday will pass the request to all middlewares without checking what they do. If you put 2 adapters in it, then they will both be called.

Given the above, I can see a couple of issues already on the gem's code:

* The adapter is called at the beginning of the stack, that should instead appear AFTER the call to the block
* The adapter is inserted in the stack even though another one could be supplied in the block.

It looks to me like the gem will need to improve the Faraday initialization, here is a possible fix:

```ruby
def configure(use_custom_adapter = false)
  @faraday = Faraday.new do |conn|
    yield conn if block_given?
    conn.adapter Faraday.default_adapter unless use_custom_adapter
  end
end
```

That's is, this way the adapter will be loaded in the correct position, and you'll be able to tell the gem to skip inserting the default adapter with the `use_custom_adapter` parameter.

**Comment by mwpastore** [comment]
Thank you for the extremely detailed and helpful answer! I'll take this back to the Munson maintainers. Have a great day.
