### ISSUE TITLE
Instances of ClientError should have a request attribute

### ISSUE THREAD

**Issue by aviflax** [lostisland/faraday#654]
It would be very helpful if these exceptions provided access to the request that lead to the exception. That way a code block that rescues these exceptions could easily log any details of the request, such as the method, URL, etc.

I’d be happy to work on this myself as a contribution but I think I’d need some guidance. I looked through the code and I was pretty confused by the `env` value — I don’t quite understand what it is. I was also confused by the `response_values` method of `Faraday::Response::RaiseError` — given that Faraday _seems_ to be mostly using OOP, it’s confusing to me that in this case a response is being represented by a hash as opposed to a `Response` class instance.

**Comment by iMacTia** [comment]
Thanks @aviflax for your suggestion.
I understand Faraday's structure can be a bit complicated at first glance and some pieces of code have not been refactored in ages (which could explain why you see hashes rather than actual classes).
I'll try to have a look myself and consider this change as I think it could add some useful information

**Comment by patientdev** [comment]
Has there been any progress on this feature? I'd like it as well and can do some work on it if need be.

**Comment by iMacTia** [comment]
Sorry for the delay guys,

I haven't marked this for a specific release so this got delayed a bit.
I still think this would be a good addition so I've now marked it for the next release.
Of course I'm open to suggestions, most important thing here is to preserve backward compatibility.

**Comment by iMacTia** [comment]
Hello guys,

A quick update on this.
I started the implementation and I realised this is more complex to achieve than expected.
There are some major issues I see here:

* `Response::RaiseError` is a response middleware. This means some information about the request are not available at that point (e.g. the request body)
* `ClientError` is a common Error class that have been around for a while, hence there are probably many component using and raising this kind of exception. Adding a new optional `request` property to it know would mean creating inconsistency (sometimes it's there, sometimes it's not, depending on who rises the exception

So after these consideration, I don't believe adding the request is the best solution anymore, I would rather suggest you to opt for another solution. Here are the 2 best I can think of at the moment:

1. Use the `logger` middleware. This will log all your requests, so you can see what happened. Bodies are not logged by default but you can enable that using the `bodies: true` option.
2. If you want to log something ONLY when you get a client error, then probably a custom middleware is the best solution

I'm gonna close the issue here but if you need any help with the above solutions then happy to provide it
