### ISSUE TITLE
Calling 'use' without 'adapter' returns nil response

### ISSUE THREAD

**Issue by jcoyne** [lostisland/faraday#665]
when I use Faraday `0.9.2` and do this:
```
conn = Faraday.new(url: my_server) do |faraday|
            faraday.use Faraday::Response::RaiseError
          end
response = conn.get(my_path)
```
Then the `response.body` and `response.status` are `nil`

If I add the adapter, then it works:
```
conn = Faraday.new(url: my_server) do |faraday|
            faraday.adapter :httpclient
            faraday.use Faraday::Response::RaiseError
          end
response = conn.get(my_path)
```

I would expect that if the adapter was required and I didn't provide it it should give me an exception
*or*
it should work with a default adapter.

**Comment by iMacTia** [comment]
Hi @jcoyne.

> I would expect that if the adapter was required and I didn't provide it it should give me an exception or it should work with a default adapter.

You're very right in this assumption, unfortunately this is an issue we're carrying over as an old implementation and we're currently planning to fix it in a future release.
The issue is that once you initialize a faraday connection using the block syntax, you are creating a middleware stack from scratch and losing the default one. This means of course that you need to explicitly specify the adapter.

You're free to join the discussion on #121 or simply add yourself as a follower so that you'll be notified once this will be addressed.

**Comment by aviflax** [comment]
This just bit me and a team-mate, we lost a good 30 minutes to this… it was pretty frustrating.
