### ISSUE TITLE
Updates to multipart-post

### ISSUE THREAD

**Issue by ioquatix** [lostisland/faraday#689]
Hi.

I'm now maintaining `multipart-post` and you are a big consumer of that library.

I would like your feedback about `multipart-post` - what's working well, what's not, and where we can go for the 3.0 release of `multipart-post`. It seems like you might be working around some issues with multipart-post so it would be good if we could improve to avoid these cases.

Additionally, I'd like to improve the module usage in multipart-post a bit - it's a bit unstructured at the moment with quite a lot of stuff defined at the top level. What are your thoughts on this?

Thanks for your time.

**Comment by ioquatix** [comment]
Specifically one thing I noticed was this:

https://github.com/lostisland/faraday/blob/067be864a67e791e6766253ce4ef3f5c740caf70/lib/faraday/upload_io.rb#L11

**Comment by ioquatix** [comment]
One more thing - perhaps we could make a shared org for the maintenance of multipart-post and faraday - and move both projects there, along with other related bits - so it's all in one area? Just a random thought.

**Comment by iMacTia** [comment]
Hi @ioquatix and thanks for he interest on Faraday.
I'm doing my best here to help as the most active Faraday maintainer at the moment, but honestly I didn't write a single line of code of the multipart middleware nor I've ever personally used `multipart-post`.

I had a quick look and the main issue I could see that prevents us from using `multipart-post` plainly is that we can't use the `Net::HTTP::Post::Multipart` class.
Reason for this are mainly 2:

* We manage multipart as a middleware, which gets called after the request object is created.
* We support different adapters, not only Net::HTTP

So from what I see my predecessors took a cherry-picking approach using only the parts of your gem strictly needed to get the job done. I'm talking about `UploadIO` and `Parts`, because `CompositeReadIO` had some sort of incompatibilities (probably due to the fact that we don't use `Net::HTTP::Post::Multipart`, see for example https://github.com/nicksieger/multipart-post/blob/master/lib/multipartable.rb#L23 which we have to do in the `CompositeReadIO` initialiser).

I'm happy to hear that you would like to make our life easier, but I'm not sure there's much you can do without drastically changing your gem structure.
One input from me in that case would be to try splitting the implementation logics from the actual HTTP library used. Try to imagine, for example, to add support for other HTTP libraries other than Net::HTTP. How much code would you need to duplicate? Is it possible to move some code from  `Multipartable` into the core classes of the gem?

**Comment by ioquatix** [comment]
@iMacTia Thanks for all that feedback.

I hear what you are saying.

Firstly - it's not my gem at all, I just stepped in to help maintain it - so I'm almost/sort of in the same boat as you, except that I have access to make changes and push a gem release as I see fit.

I think what I'd like to do is try to extract some of that functionality into it's own class/module as you say, to make it more easily reusable.

I'll have a think about it. The first goal I had was to get the code actually passing tests on all 2.x rubies, now that's done, I'll revisit the structure of the code.

**Comment by iMacTia** [comment]
That's great news and yes, I completely understand your situation.
If you manage to separate the core logics from the actual "adapters" (as we call them) implementation than we might get rid of a lot of code and simply use your core classes in the next Faraday version.
I'll keep this issue open for future updates from you.

Thanks!

**Comment by iMacTia** [comment]
Hi @ioquatix,
just wanted to let you know that I'm closing this issue for now as I haven't heard from you since last year. Feel free to reopen if you have any update though!
