### ISSUE TITLE
(How) is no_proxy supported?

### ISSUE THREAD

**Issue by JasonBarnabe** [lostisland/faraday#700]
Version 0.12.0 in the release notes says "Proxy feature now relies on Ruby URI::Generic#find_proxy and can use no_proxy ENV variable (not compatible with ruby < 2.0)". Great! However I noticed [this line](https://github.com/lostisland/faraday/blob/3268aca539ea5a746c3aaef9b3a6d7db78d4ee27/lib/faraday/connection.rb#L447):
```ruby
warn 'no_proxy is unsupported' if ENV['no_proxy'] || ENV['NO_PROXY']
```
So is `no_proxy` supported or not? Or maybe supported sometimes? Please fix or document this.

**Comment by iMacTia** [comment]
Hi @JasonBarnabe,

I'm sorry about the confusion. If you check when that method is actually called, you'll see that function can only be reached if `URI.parse("").respond_to?(:find_proxy)` is not true (so Ruby < 2.0) or if you don't provide the url when you initialise Faraday (in which case we can't guess it for you).

So the documentation doesn't go too much into details but simply say things as they are: we support the no_proxy automatically, but only starting from Ruby 2.0 😄

**Comment by JasonBarnabe** [comment]
OK, thanks for the info. I did see `URI.parse("").respond_to?(:find_proxy)` and was wondering what that could possibly mean :)

**Comment by iMacTia** [comment]
Oh I see. Simply the method `find_proxy` was introduced in Ruby 2.0 so if it's not there means we're in Ruby <=1.9 😃
We preferred to check this way instead than checking the ruby version because this way it might work also for other ruby interpreters (e.g. JRuby) if they support this function, or because you can monkey-patch older versions to support it if you need

**Comment by pboling** [comment]
I am getting this output on Ruby 2.3.3 currently.  Is this a regression?
