### ISSUE TITLE
no_proxy does not work when using Faraday.get

### ISSUE THREAD

**Issue by JasonBarnabe** [lostisland/faraday#701]
In this test, 404 is the expected response. 503 is the response from the proxy.
```
[web@CDLXUTL301 Canadadrugs-Build]$ bundle show faraday
/home/web/.rvm/gems/ruby-2.3.3@canadadrugs/gems/faraday-0.12.1
[web@CDLXUTL301 Canadadrugs-Build]$ RAILS_ENV=test rails console
Loading test environment (Rails 5.0.3)
[1] pry(main)> ENV['http_proxy']
=> "http://lxgw103.candrugcorp.net:3128"
[2] pry(main)> ENV['no_proxy']
=> "localhost,127.0.0.1,172.22.24.151,cdlxutl301.candrugcorp.net"
[3] pry(main)> Faraday.get('http://localhost:8983/select?wt=json&q=*%3A*').status
no_proxy is unsupported
=> 503
[4] pry(main)> Faraday.new(url: 'http://localhost:8983').get('http://localhost:8983/select?wt=json&q=*%3A*').status
=> 404
```

**Comment by iMacTia** [comment]
Hi @JasonBarnabe,

when you call Faraday.get without first initialising the connection, a Faraday::Connection with no url is created to perform the request. This causes the `find_default_proxy` method to be triggered, without no_proxy support (second case I highlighted in #700).
This was raised (https://github.com/lostisland/faraday/pull/670#pullrequestreview-27191603) and should be fixed in the next small release.
For the time being, you can make it working using the `Faraday.new` initialiser as you noticed already.

However your code can be simplified a bit:

```ruby
Faraday.new('http://localhost:8983').get('/select?wt=json&q=*%3A*').status
```

**Comment by iMacTia** [comment]
@JasonBarnabe I'm sorry this was a bit later than expected, but I think I finally got on top of the issue and nicely refactored the environment proxy management to work efficiently in all cases.
A little harder than what I initially thought 😅
I'm going to add new tests before merging #712, but please feel free to give it a shot in your app and leave some feedback
