### ISSUE TITLE
Remove Faraday::Utils.default_params_encoder=

### ISSUE THREAD

**Issue by mguterl** [lostisland/faraday#720]
We recently encountered a [bug](https://github.com/twilio/twilio-ruby/issues/328) caused by twilio-ruby which uses Faraday. The Twilio HTTP adapter changed Faraday::Utils.default_params_encoder inside of their HTTP adapter initialize method. This made the bug particularly insidious to track down because it only broke our other libraries using Faraday after having run a sidekiq job that used twilio. 

After reflecting on the experience I wondered if it makes sense to even have the ability to change the default on such a global level. Any time a library changes the default, they risk breaking every other library that is depending on the default behavior. I think it makes sense to provide a default, but if a user wants something different, it should be specified on a per request basis and not modified globally.

**Comment by iMacTia** [comment]
Hi @mguterl.

I completely understand your frustration, but I hope you'll understand that I can't remove an established API simply because a gem made an improper use of it.
Any OO-developer building a library knows that you should never set default values for other libraries, because the result is exactly what you're experiencing with the `twilio-ruby` gem.

This functionality can be dangerous, but it can also be really helpful for others.
The "rule of thumb" in this case is that you should change "default_" values only if you're the one controlling the entire application. It's absolutely a BAD idea doing it when you're building a gem that other people will use in their application.

And to provide an analogy, think about Rails's `ActionMailer`. You can provide most of the configuration once at application level and it will affect all mailers in your app, or you can define it separately on each mailer (usually the latter have priority). Now, if you want to build a gem that provides a `Mailer`, where would you put the configuration for that mailer? It would be foolish to override the Rails application generic configuration, but you can still do that, if you want...

I don't think there nothing wrong with providing `Faraday::Utils.default_params_encoder=`, the real issue here is the way others use it.
