### ISSUE TITLE
HTTP/2 Streaming and async requests/responses

### ISSUE THREAD

**Issue by philsturgeon** [lostisland/faraday#734]
Hey there! I've been playing around with net-http2 and it's fantastic. So many people seem scared to try and use HTTP/2, but it's here, now, we can use it, and we should be using it. 

Even though Rails and Rack seem to not really support HTTP/2 properly yet, anything behind Fastly, Cloudflare, etc have persistent connections enabled, meaning that it would be great for Faraday to start allowing for async connections.

For [my little benchmark](https://gist.github.com/philsturgeon/ea4c3966731c8e2e92e70b11fe10d1bc), making 20 connections took ~3 seconds, instead of ~12. 

I'd just work on a PR and send in an adapter for net-http2, but it requires a new API for the gem, as async calls and promises are a little different.

```
client = NetHttp2::Client.new(host)

n.times do
  # prepare request
  request = client.prepare_request(:post, '/check', body: JSON.generate(params), headers: {
    'content-type' => 'application/json'
  })

  client.call_async(request)
end

# Wait for all outgoing stream to be closed
client.join

# close the connection
client.close
```

So, I would absolutely love to put the time into working on this, as it's important for me to keep the use of various faraday middlewares I've been building as [part of WeWork's stack](https://engineering.wework.com/introducing-we-call-a-ruby-gem-for-making-http-calls-awesome-4ce3f7e54f46). 

Before I get stuck in, I would like a thumbs up, tips on direction, etc. 

Or maybe you're already working on this and I can just go for a bike ride instead. Who knows! 😄

**Comment by iMacTia** [comment]
Hi @philsturgeon, thanks for bringing this to my attention!
I'm keeping an eye on the HTTP/2 protocol and its evolution, but for now it's sitting in the "future stuff" pile and I'm not planning any work on it in the short term.
I agree with you though that it would be great to have Faraday supporting it with `net-http2`.
The good news is that Faraday is "async-ready" as some of the adapters can already process asynchronous requests. That's why the `on_complete` API was introduced.

Now, my understanding is that `net-http2` is an external gem, differently from `net-http` which is built-in on ruby. This make your dream even easier to realise as it means that we can simply manage this as a separate adapter. We can have a `:net_http2` adapter side to side with the default `:net-http` one and anyone will be able to simply "opt-in" when initialising the connection.

That said, I'd be more than happy for you to create a new adapter that uses the `net-http2` gem as a dependency, but I'll ask you something more.
The long-term plan is to move all adapters outside of faraday and make them separate, independent gems. You can see an example of this with Typhoeus that ships with its own [Faraday Adapter](https://github.com/typhoeus/typhoeus/blob/master/lib/typhoeus/adapters/faraday.rb). Typhoeus also support parallel (async) requests, so that would be a good inspiration for your `net-http2` adapter.

The only thing that would be different in your case would be that you'll need to create a separate `faraday-net-http2` gem, unless the guys from `net-http2` allow you to put the adapter directly on their gem 😄 

This way, you'll have total freedom while building your gem and we'll of course mention it together with the other adapters in the Faraday README. Moreover, once you're done with the gem, you can add some tests here in Faraday to test the integration with it, so that we don't break it while adding new features.

I'm also happy to contribute in case there's any change needed in Faraday itself to support the new adapter 👍

**Comment by iMacTia** [comment]
Forgot to close this after my answer 😄
@philsturgeon did you decide to go on and create the adapter in the end?

**Comment by philsturgeon** [comment]
Absolutely fine. I'll get #740 complete with tests, then use that to get started with the net-http2 adapter. 👍

**Comment by iMacTia** [comment]
Sounds great, really looking forward to it!
Please feel free to keep me in the loop when you create the new repo as I would like to contribute if time allows me to 👍

**Comment by philsturgeon** [comment]
@iMacTia can we reopen this one? I was snowed under dealing with gigantic piles of nonsense and firefighting at that Ruby job, just never got time to sit down and knock this out. Now I don't ruby. 😢 

HTTP/2 is still massively important and I'm happy to [donate a _lot_ of trees](https://ecologi.com/philsturgeon) to whomstever gets this done.

**Comment by iMacTia** [comment]
Hey @philsturgeon, things evolved quite a lot over the last years and Faraday now has better support with external adapters 🎉 !
If you check the `gemspec`, you'll notice we expose the `spec` and `examples` folders. Those are for unit and integration tests respectively.
You can see an example of an adapter built leveraging the `spec` folder here: https://github.com/lostisland/faraday-http

So nothing really to do here in Faraday for now, unless I'm missing something.
We just need a volunteer to build the adapter gem now, but that will happen entirely on a new repo 👍

**Comment by akostadinov** [comment]
Is faraday still lacking HTTP/2 support? I can't find any other info.

**Comment by iMacTia** [comment]
@akostadinov Faraday doesn't really need to do anything to support HTTP/2.
All you need to do is to pick and use an adapter that uses HTTP/2, like [async-http](https://github.com/socketry/async-http-faraday) or [httpx](https://honeyryderchuck.gitlab.io/httpx/wiki/Faraday-Adapter)

**Comment by exv-minhlv** [comment]
@iMacTia If I not install gem httpx, Can I use [async-http](https://github.com/socketry/async-http-faraday) or [httpx](https://honeyryderchuck.gitlab.io/httpx/wiki/Faraday-Adapter) with Faraday ?
I try find document, but i not found it.
