### ISSUE TITLE
Case-sensitive headers being mutated

### ISSUE THREAD

**Issue by NickOttrando** [lostisland/faraday#751]
Faraday automatically downcases headers' keys' letters in the middle of a word when instantiated.

* Faraday Version: 0.12.1
* Ruby Version: 2.3

## Issue description
I need a header to keep capitalization, and faraday automatically downcases letters in middle of a word when instantiated. for example, header with key xYz_aBc will be formatted as "XYz-Abc", I need to keep the Y's capitalized. Is there a certain file I can overwrite to get this behavior? 

## Steps to reproduce
```
 Faraday.new("http://xyz.com", headers: {xYz_aBc: "d"}).headers
=> {"Xyz-Abc"=>"d", "User-Agent"=>"Faraday v0.12.1"}
```

**Comment by iMacTia** [comment]
Hi @NickOttrando I got a similar issue just days ago but in that case the user wanted to keep downcase letter. It turned out the issue was not in Faraday, but in the underlying adapter (in that case, `Net::HTTP`).
Are you able to perform the request keeping the capitalisation using the plain Net::HTTP without Faraday?

**Comment by NickOttrando** [comment]
@iMacTia thanks, this helps.

**Comment by katmsft** [comment]
@iMacTia Although the header keys should be case-insensitive, it is possible for the server to be case-preserving.
Rather than changing the case of the header keys, the HTTP client should always compare the keys as case-insensitive strings, while passing them to the user or server as is, or at least make this an option for the user.
A user scenario would be that the user want to set the metadata for a resource, specifying a header to be `"MyMetaKey" => "MyMetaValue"`. Later user can also use `"Mymetakey"` as the key to change the value that has been set by the previous request. However, when user gets this key, he would always get lower case key which is silently converted by Faraday, causing it a key mismatch and usually hard to debug.
@NickOttrando Is is possible for you to reopen the issue or should I create another issue for the matter?

**Comment by iMacTia** [comment]
Hi @katmsft I'm not really sure I completely understand your user-scenario.
Could you please provide a quick code example to show that?
We can decide if opening an issue after that
