### ISSUE TITLE
Include #604 in a release

### ISSUE THREAD

**Issue by zgalor** [lostisland/faraday#764]
I could really use HTTP streaming API. 
I have a use case that is blocking on this. It would determine if we keep using faraday or will be forced to switch to a different client.

I see this PR https://github.com/lostisland/faraday/pull/604 was merged into 1.0
I understand releasing 1.0 will take relatively a long time.

According to the PR, it seems the change should be safe to backport [1]
Could you backport it to a minor closer release?

BTW thanks for all the great work on this gem!

[1] https://github.com/lostisland/faraday/pull/604/files#diff-3424bc6f644386c2e3eb952f2d65b597R17

**Comment by iMacTia** [comment]
Hi @zgalor 
Main reasons for me being reluctant in back-porting this are:

* The feature have a relatively small test coverage
* It only supports `Net::HTTP` adapter and throws a `warn` in all the others
* It has not been production tested
* If I do back-port it, that means I'll also need to officially maintain it.

This is also why I'm keeping it from being released until v1.0 where I'll feel more comfortable thanks to the release candidates that will precede the final release. Plus all adapters except for `Net::HTTP` will be moved to external gems, reducing the confusion.

Now, I completely understand your position, so here are some possible solutions for you:

1. You use the `1.0` branch in your app. Not really production-safe to be honest, but should be OK if you avoid running `bundle update`.
2. You fork Faraday and use your own fork. Same as above, but this gives you more control. You can also pull changes if you need (e.g. a bug fix). No surprises in production.
3. You monkey-patch faraday to add these changes on top of the latest release. Most of the PR changes are not needed if you use `Net::HTTP` so you just need to add some of them. This way you can still update faraday (works on 0.x versions will almost stop until v1.0 anyway).

Of course all the solutions above would only be temporary and you'll be able to upgrade to v1.0 as soon as we have a RC or the final version released.
I understand they might not be ideal, but is any of the 3 solutions above reasonable for you?

**Comment by zgalor** [comment]
@iMacTia Thanks for explaining so thoroughly.
Unfortunately, none of those solutions is applicable to our needs.
Is there a timeline for 1.0?

**Comment by iMacTia** [comment]
@zgalor no problem, sorry that's probably not the answer you expected but I wanted to be clear rather than just saying "no" without any reason.
Regarging a possible timeline for Faraday, I've created a [Project](https://github.com/lostisland/faraday/projects/1?) to track it properly but it's hard of course to estimate a completion date as I'm the only one working on it with some help from @olleolleolle, and we both donate our free time to it which varies according to how busy we are with work.

I promised myself to enter a "focused" phase where changes to 0.x versions will be held so we can put all our efforts in version one.
At things stands now, I'd roughly estimate we'll need 3-6 months to have the first release candidate, but please don't take this as a commitment for the reasons above.
Having more contributors will surely help speeding things up.

I'm sorry if that doesn't meet your needs, you're more than welcome to help us getting there faster.
