### ISSUE TITLE
Advice on how to implement adapter

### ISSUE THREAD

**Issue by ioquatix** [lostisland/faraday#766]
I'm implementing an adapter for Faraday on top of Async (https://github.com/socketry/async).

The current implementation is here: https://github.com/socketry/async-http-faraday/blob/master/lib/async/http/faraday/adapter.rb

I was wondering, what is the correct way to register the adapter? I've done it at the very bottom.

Is there some way to avoid using a symbol and just directly write in `Async::HTTP::Faraday::Adapter`?

What are the requirements of `env[:body]`? I was hoping it would respond to `.each` and return chunks of data (similar to how rack response body works).

Finally, apart from the fact the adapter is incomplete, do you have any other suggestions?

**Comment by iMacTia** [comment]
Hi @ioquatix.
First of all let me say that this project looks great!
Thanks for taking the time to consider writing a Faraday Adapter.
I had a quick look and it looks to me like you followed the most important requirements:

* The adapter should inherit from `Faraday::Adapter`
* The adapter should process the request and call `save_response` at the end

The adapter registration is completely optional as it simply enables other to call your adapter with the symbol, but they can always refer to it as a class:

```ruby
Faraday.new(...) do |builder|
  builder.adapter Async::HTTP::Faraday::Adapter
  # OR
  builder.adapter :async_http
end
```

You don't need to reopen the Faraday::Adapter class to register the middleware, you can instead call the method in one line:

```ruby
Faraday::Adapter.register_middleware :async_http => Async::HTTP::Faraday::Adapter
```

Regarding the `env[:body]`, that's just a simple `String`. Since you mention "chunks of data" I suppose you're referring to streaming responses. That feature will only be available in Faraday v1.0 and will be supported by a separate callback method. You can see the PR [here](https://github.com/lostisland/faraday/pull/604) with a [usage example](https://github.com/lostisland/faraday/pull/604/files#diff-04c6e90faac2675aa89e2176d2eec7d8) and an [implementation example](https://github.com/lostisland/faraday/pull/604/files#diff-d8775963a7e225c40196fd205b28a626).

**Comment by ioquatix** [comment]
Thanks that is all really helpful.

Is there information about parallel manager? Will it affect requests done in different fibers?

**Comment by iMacTia** [comment]
I have to be honest here @ioquatix, I have no idea on how the `parallel_manager` works as I haven't had a chance to look at it yet.
My suggestion is to check the [Wiki page](https://github.com/lostisland/faraday/wiki/Parallel-requests) and the implementation for EMSynchrony, EMHttp and Typhoeus adapters.

Sorry I can't be of much help in this case.

**Comment by iMacTia** [comment]
@ioquatix I'm closing this for now but please let me know how works progress with your adapter and we could feature it on Faraday's README

**Comment by ioquatix** [comment]
Thanks.

The adaptor works fine, we have it in production.

Feel free to add a link in the README. Hopefully soon we will also support HTTP2.

**Comment by ioquatix** [comment]
It's still early days I will work on it more when I have time to improve SSL and other things :)

**Comment by iMacTia** [comment]
Congratulations, great work 👍 !
In that case then feel free to create a PR to add it to the README when you feel it's ready for the masses 😄, I understand you don't want users to try it and then change their mind because of bugs/issues
