### ISSUE TITLE
Does Faraday keep sending requests until it gets a response?

### ISSUE THREAD

**Issue by j-jackson** [lostisland/faraday#771]
I have added a third party service to my rails app which allows users to register domains and I'm trying to debug an issue where I randomly get banned for 10 minutes due to two many requests.

Usually If I enter a domain and click register I get a response back within a few seconds and the process complete, but every now and then it appears to hang while registering before it finally errors out with the ban notice. 

- I am the only one testing the app.
- I only click the button once.

Does Faraday keep trying until it gets a response back?  if so, is there a way I can limit it?

Below is my client code:

```ruby  def self.client
  Faraday.new(url: API_URL) do |conn|
    conn.response :logger
    conn.options.open_timeout = 5  
    conn.response :xml,  :content_type => /\bxml$/
    conn.response :xml, :parser_options => { :symbolize_names => true }
    conn.adapter Faraday.default_adapter
  end
```

Thanks!

**Comment by iMacTia** [comment]
Hi @j-jackson,

Faraday should not do that by default but this reminds me of an issue I investigate some time ago.

In `Net::HTTP` (Faraday's default adapter) if the call is performed and some particular exceptions occur (e.g. timeout), and the method used is idempotent (like GET), then the request is retried once.
You can see this [here](https://github.com/ruby/ruby/blob/ruby_2_3/lib/net/http.rb#L1436), together with the full list of exceptions.

Since you're noticing that
> every now and then it appears to hang while registering

I think this is somehow linked with `Net::HTTP`'s automatic retry.
I don't see a way to disable this in the library, so you can either:

1. Monkey-patch `Net::HTTP` removing `GET` from `IDEMPOTENT_METHODS_`
2. Try with a different adapter

Let me know if you have any update, will keep the issue open for now.

**Comment by j-jackson** [comment]
Thank you @iMacTia !

I have replaced `Net::HTTP` with typhoeus so hopefully thats enough.

**Comment by philsturgeon** [comment]
Long version! https://engineering.wework.com/ruby-users-be-wary-of-net-http-f284747288b2 

There is now a max_retries setter, added in ruby 2.5.0. 

@iMacTia This is a tricky topic but when the NetHTTP adapter is set, Faraday should set this to 0, then if the retry middleware is used then it should use that value. 

An alternative solution would be to let defaults be default and only set this if the retry middleware is used, but... I don't like that. Folks are still magically sometimes getting retries... The only upside is that this approach does not change default behaviour for folks who right now are relying on the nethttp retry. I'm not sure if many folks are, because all the responses to that article above are "woah wtf it does this?!" and I've only ever seen two or three people who knew about it. 🤷‍♂️

**Comment by philsturgeon** [comment]
Related to #612

**Comment by iMacTia** [comment]
Thanks for the update @philsturgeon.
I agree, that would help avoiding the "surprise" effect and standardise adapters behaviour.
And that's also what we planned in #612, but the release version was not known at that point.
I'll close this issue and create a new one specifically for this.
