### ISSUE TITLE
Rack adapter passes incompatible input

### ISSUE THREAD

**Issue by milgner** [lostisland/faraday#785]
## Basic Info

* Faraday Version: 0.14.0
* Ruby Version: 2.3.6

## Issue description
Rack expects the `env[:input]` to [have a `set_encoding` method](https://github.com/rack/rack/blob/2-0-stable/lib/rack/mock.rb#L139). When a client passes a Hash (using the [oauth2](https://github.com/oauth-xx/oauth2) gem here), this fails.

## Steps to reproduce
Switch to the rack adapter, using rack-test and pass in a hash to the request method.

I'm really familiar with faraday itself, so I'm not sure what the correct approach would be. Just ugly hacking the rack adapter to read

```ruby
        rack_env = {
          :method => env[:method],
          :input  => env[:body].respond_to?(:read) ? env[:body].read : env[:body].to_json,
          'rack.url_scheme' => env[:url].scheme
        }
```

seems to fix the problem but I guess that it is quite dangerous to assume that `.to_json` is what's desired here. It might be better to fix this problem upstream (`oauth2' gem, in this case), but I wanted to let you know nonetheless since other adapters seem to work with this kind of API usage.

**Comment by iMacTia** [comment]
Hi, thanks for reporting!
This definitely needs more investigation as to where the actual issue lies.
I’ll try to have a look in the next days and get back!

**Comment by iMacTia** [comment]
Hi @milgner, sorry for the delay in the response (mainly due to the Easter break).
I had a look and I can now confirm that `:input` is expected to be a String or IO-like (see https://github.com/rack/rack/blob/2-0-stable/lib/rack/mock.rb#L18).
Now, I think the surprise is that the Hash is being forwarded down until the adapter.

I'm not really sure of how you're configuring `oauth2`, but I suppose you're passing a `connection_build` block?
If that's the case, you're probably missing the body encoding. You can fix that by telling your builder to use something to encode your request body:

For url-encoding: `builder.request :url_encoded`
For JSON: `builder.request :json`

Let me know if that fixes your issue

**Comment by iMacTia** [comment]
Closing assuming the above worked but feel free to reopen if not 👍
