### ISSUE TITLE
Pre-formatted path with query string gets mangled before sending to server

### ISSUE THREAD

**Issue by doughsay** [lostisland/faraday#804]
https://github.com/lostisland/faraday/blob/f08a985bd1dc380ed2d9839f1103318e2fad5f8b/lib/faraday/parameters.rb#L117

This is causing us a lot of pain right now during an upgrade.  I'm effectively doing this:

```ruby
client = Faraday.new(url: base_url)
client.get("/path?query")
# where query is something like: "foo[0][bar]=one&foo[1][bar]=two"
```

i.e. I'm passing in an already formatted path with query string to `get`.  But it appears that somewhere along the way, `Faraday::NestedParamsEncoder#decode` gets called on my string, which strips out my well places integers (presumably because of this `dehash`?).  What the remote server ends up receiving is: `"path?foo[][bar]=one&foo[][bar]=two"`.

How can I force Faraday to leave my path alone?

**Comment by iMacTia** [comment]
Hi @doughsay, I'm sorry to hear you're having issues with this.
Faraday takes the path you provide when calling `get` and parses it using the `ParamsEncoder`. This is because we allow to provide params in different ways so we can merge them together at that point.
The default params encoder `Faraday::NestedParamsEncoder` unfortunately doesn't behave as you expect as it's made compatible with Rails and I suppose the server you're trying to call is based on a different technology.

The easiest solution in this case is to write your own `ParamsEncoder` as I explained in this comment: https://github.com/lostisland/faraday/issues/676#issuecomment-284743399

It's actually easier than it looks like, as you can inherit from the default one and simply change the way arrays are encoded.

Let me know if this helps

**Comment by doughsay** [comment]
@iMacTia thanks for pointing me in the right direction.  I've implemented my own custom ParamsEncoder as you suggested that falls back on `Rack::Utils.parse_nested_query` for decoding.  This solved my issue, thanks!
