### ISSUE TITLE
Expose `pool_size` as a config option for net_http_persistent

### ISSUE THREAD

**Issue by col** [lostisland/faraday#833]
## Basic Info

* Faraday Version: 0.15.3
* Ruby Version: jruby-9.1.17.0

## Issue description
The constructor for Net::HTTP::Persistent contains a `pool_size` param. There is currently no way to set this when using Faraday.

Net::HTTP::Persistent constructor definition here:
https://github.com/drbrain/net-http-persistent/blob/0e5a8fb8a27deff37247ddb3bc5e6c9e390face5/lib/net/http/persistent.rb#L505 
```ruby
def initialize name: nil, proxy: nil, pool_size: DEFAULT_POOL_SIZE
  ...
end
```

Usage of Net::HTTP::Persistent in the Faraday::Adapter::NetHttpPersistent:
https://github.com/lostisland/faraday/blob/88de44ebe3c40f9050553ce7c0018990b92c2f38/lib/faraday/adapter/net_http_persistent.rb#L11

## Steps to reproduce
N/A

## Solution ?

I don't have a solution for this yet but I'm happy to submit a PR if someone can suggest the right way to approach this. 

An example usage is here:
https://github.com/lostisland/faraday#nethttppersistent
```ruby
conn = Faraday.new(...) do |f|
  f.adapter :net_http_persistent do |http| # yields Net::HTTP::Persistent
    http.idle_timeout = 100
    http.retry_change_requests = true
  end
end
```

The problem with this is that it yields an already initialized Net::HTTP::Persistent object so it's too late to provide the additional constructor param. 

Faraday::Adapter::NetHttpPersistent does have access to `env` when it's creating the instance of Net::HTTP::Persistent though. Is there an appropriate way to add a `pool_size` config to the `env`?

**Comment by iMacTia** [comment]
Hi @col, thanks for raising this.
No need to stick this information into the `env`, we can use `connection_options`.
This instance variable is already supported by some of the adapters and can easily be added to `Net::HTTP::Persistent` too. You can see how it works by running a quick search: https://github.com/lostisland/faraday/search?q=connection_options&unscoped_q=connection_options

Usage would be something like:

```ruby
conn = Faraday.new(...) do |f|
  f.adapter :net_http_persistent, pool_size: 100
end
```

If you manage to understand how it works, feel free to open a PR otherwise I'll try to find some time over the weekend, it should be a 5 mins job to add it in

**Comment by col** [comment]
Great. That’s exactly what I was looking for. I’ll get it done in the next
few hours and submit a PR.

**Comment by araslanov-e** [comment]
:+1:
