### ISSUE TITLE
Trying to run faraday with em-http adapter throws error

### ISSUE THREAD

**Issue by Struki84** [lostisland/faraday#911]
## Basic Info

* Faraday Version: 0.15.4
* Ruby Version: 2.4.0

## Issue description
Trying to run simple get request using em_http adapter. 
``` 
request = Faraday::Connection.new(:url => 'https://www.sintezis.co') do |settings|
    settings.adapter :em_http
end

response = request.get '/'
```

```
RuntimeError - missing dependency for Faraday::Adapter::EMHttp: cannot load such file -- em-http:
```

**Comment by iMacTia** [comment]
Hi @Struki84, as Faraday supports multiple adapters, we don't put them in the list of dependencies, otherwise your project would need to install ALL the possible adapters, even if you use only one of them.
For this reason, when you use an adapter which is different from the default `net_http`, you'll need to add the correspondent gem to your Gemfile.
In your case, you simply need to add the `em-http` gem:

```
gem 'em-http-request', '>= 1.1', require: 'em-http'
```

**Comment by Struki84** [comment]
OK great! But it would be helpful to point this out in the Readme.md. It would have saved me a days work :/. I think there is smth in general, but it should be point out what gems should be installed for desired adapter.

**Comment by olleolleolle** [comment]
@Struki84 In the Faraday Middleware repo's README, there's a nice table.

Could you inspect that, and build something like it, as a PR, to this repo's README? 

See here for how it looks, and what it contains: https://github.com/lostisland/faraday_middleware#dependencies 

Hope this inspires!

**Comment by Struki84** [comment]
OK, will look into it.
