### ISSUE TITLE
Faraday net_http_persistent not working in Phusion Passenger

### ISSUE THREAD

**Issue by slashd0t** [lostisland/faraday#965]
## Basic Info

* Faraday Version: 0.15.4
* Ruby Version: 2.5.0
* Passenger: 6.0.2

## Issue description
I have a rails app with api endpoint that will authenticate to the remote server by using **api_key** in order to authorized the current user.
This endpoint is using Faraday to connect to the remote server. See example below:
```
 HEADERS = {
      'X-Version' => 'V1',
      'X-API-Key' => 123456,
      'Content-Type' =>'application/json'
}
uri = "https://api.remoteserver.com/VerifyAPIKey"
conn = Faraday.new() do |f|
   f.adapter :net_http_persistent do |http|  
   http.idle_timeout = 100
 end
end
@response = conn.post do |req|
  req.url URI(uri)
  req.headers = HEADERS
  req.body = body
end
```
If you notice, I configure the adapter of Faraday using **net_http_persistent** because I'm running an open-source Phusion Passenger server and we need a persistent connection because the Passenger is a **multi-process** which means it will spawn **one** or **more processes** as the load increases. However at first request the api was successfully authorized(see processID #26698) but on the next request I got **authorization error** (processID #64121)
See the logs below:
I, [2019-04-01T18:20:29.611996 #26698]  INFO -- Authorization is finished successfully.
I, [2019-04-01T18:20:29.611996 #26698]  INFO Thread with name "MsgsQueue worker #47338607938600"
I, [2019-04-01T18:20:29.611996 #26698]  INFO Thread with name "MsgsQueue worker #47338625106140"
I, [2019-04-01T23:20:09.341415 #64121]  INFO Authorization error. Need to authenticate first!
I, [2019-04-01T23:20:09.341415 #64121]  INFO Thread with name "LogsSender worker #47158391867980" is terminated!
I, [2019-04-01T23:20:09.341415 #64121]  INFO Thread with name "LogsSender worker #42158391867991" is terminated!

Is there any settings in Faraday that I'm missing ?
Any help would be greatly appreciated. Thanks

**Comment by olleolleolle** [comment]
The example code looks like it's missing something, here: 

```ruby
conn = Faraday.new() do |f|
   f.adapter :net_http_persistent do |http|  
end
```

The block with this opening `do |http|` is not closed; this is a typo, right?

(I'm asking, so that other readers can help you better with your actual question.)

**Comment by slashd0t** [comment]
> The example code looks like it's missing something, here:
> 
> ```ruby
> conn = Faraday.new() do |f|
>    f.adapter :net_http_persistent do |http|  
> end
> ```
> 
> The block with this opening `do |http|` is not closed; this is a typo, right?
> 
> (I'm asking, so that other readers can help you better with your actual question.)

minor typo error.. i edited it. thanks

**Comment by technoweenie** [comment]
If I'm understanding correctly, it sounds like there are a couple potential issues:

1. You're expecting Faraday and Net::HTTP::Persistent to use a single TCP connection to talk to your server across multiple requests. Since your server is spawning multiple processes, perhaps there is no persistent TCP connection?
2. Your API requires requests to hit the exact same server process to authorize requests.

First, HTTP is a stateless protocol. Even if a client and/or server manages persistent TCP connections in a pool, the application code will treat each request as a separate entity. User agents have to attach some kind of authentication to each request, whether it's a session cookie or API token. If you're looking for long running, stateful network connections, Faraday is not going to work for this. Faraday is designed around (usually) short lived request/response HTTP interactions.

Second, Faraday leaves the actual networking and HTTP protocol stuff to the various HTTP libraries. You can access the `Net::HTTP::Persistent` object inside the the adapter block to see some of its internal state:

```ruby
require 'faraday'
require 'pp'
f = Faraday.new do |f|
  f.adapter :net_http_persistent do |http| 
    pp http
  end
end
res = f.get 'http://example.com' ; res.status
```

That uses the prettyprint package to dump out something like this:

<details>
<summary>`Net::HTTP::Persistent` internal state</summary>

```
#<Net::HTTP::Persistent:0x007fbcb9034120
 @ca_file=nil,
 @ca_path=nil,
 @cert_store=nil,
 @certificate=nil,
 @ciphers=nil,
 @debug_output=nil,
 @generation=0,
 @headers={},
 @http_versions={"example.com:80"=>"1.1"},
 @idle_timeout=5,
 @keep_alive=30,
 @max_requests=nil,
 @name="Faraday",
 @no_proxy=[],
 @open_timeout=nil,
 @override_headers={},
 @pool=
  #<Net::HTTP::Persistent::Pool:0x007fbcb902fd00
   @available=
    #<Net::HTTP::Persistent::TimedStackMulti:0x007fbcb902f300
     @create_block=
      #<Proc:0x007fbcb902fbc0@/Users/rick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:525>,
     @created=1,
     @enqueued=1,
     @key=:"connection_args-70224267278720",
     @lru={["example.com", 80]=>true},
     @max=1792,
     @mutex=#<Thread::Mutex:0x007fbcb902f210>,
     @que=[],
     @ques=
      {["example.com", 80]=>
        [#<Net::HTTP::Persistent::Connection:0x007fbcb7884f48
          @http=#<Net::HTTP example.com:80 open=true>,
          @last_use=2019-04-02 08:49:55 -0600,
          @requests=3,
          @ssl_generation=0>]},
     @resource=#<Thread::ConditionVariable:0x007fbcb902f1e8>,
     @shutdown_block=nil>,
   @key=:"current-70224267278720",
   @key_count=:"current-70224267279660-count",
   @size=1792,
   @timeout=5>,
 @private_key=nil,
 @proxy_uri=nil,
 @read_timeout=nil,
 @retry_change_requests=false,
 @reuse_ssl_sessions=true,
 @socket_options=[[6, 1, 1]],
 @ssl_generation=0,
 @ssl_timeout=nil,
 @ssl_version=nil,
 @verify_callback=nil,
 @verify_depth=nil,
 @verify_mode=1>
```

</details>

That output above should give you an idea of what persistent connections `Net::HTTP::Persistent` is holding.

Does that help, or did I misunderstand the problem?

**Comment by slashd0t** [comment]
@technoweenie Thank you so much sir for a brief explanation about the Net::HTTP::Persistent. I thought that using this method will solved my issue in multi-process in opensource Passenger.

**Comment by iMacTia** [comment]
Reading above it seems like there's no real issue with Faraday and the problem was due to the usage of the `Net::HTTP::Persistent` adapter, so I'm closing this one assuming @technoweenie reply clarified that.
If that's not the case, please feel free to reopen
